### ISSUE TITLE
Need help?

### ISSUE THREAD

**Issue by jdalt** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#10]
<a href="https://github.com/andyinabox"><img src="https://avatars1.githubusercontent.com/u/151084?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [andyinabox](https://github.com/andyinabox)**
_Monday Jun 01, 2020 at 17:01 GMT_
_Originally opened as https://github.com/jdalt/twin-cities-aid-distribution-locations/issues/2_

----

Would be happy to help with this proj if there's anything needed.

**Comment by jdalt** [comment]
<a href="https://github.com/maxine"><img src="https://avatars3.githubusercontent.com/u/23054741?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [maxine](https://github.com/maxine)**
_Monday Jun 01, 2020 at 17:24 GMT_

----

+1

**Comment by jdalt** [comment]
<a href="https://github.com/andyinabox"><img src="https://avatars1.githubusercontent.com/u/151084?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [andyinabox](https://github.com/andyinabox)**
_Monday Jun 01, 2020 at 17:32 GMT_

----

@jdalt I'm going to start adding issues for things I think could improve the map. Plz let me know if there's anything I can do to be more helpful, like managing PRs. Or if this just isn't really helpful at all :)

**Comment by jdalt** [comment]
<a href="https://github.com/andyinabox"><img src="https://avatars1.githubusercontent.com/u/151084?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [andyinabox](https://github.com/andyinabox)**
_Monday Jun 01, 2020 at 18:02 GMT_

----

hi @maxine are you working on this too rn? lets keep in touch so we don't duplicate work. :smile_cat:. i'm gonna try and make issues and assign to myself if i'm working on them

**Comment by jdalt** [comment]
<a href="https://github.com/jdalt"><img src="https://avatars2.githubusercontent.com/u/2358067?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jdalt](https://github.com/jdalt)**
_Monday Jun 01, 2020 at 18:05 GMT_

----

@andyinabox @maxine 
Do you two want to be direct contributors on the repo? I'm literally going to pass out very soon and if you can keep pushing out good changes I'm happy to hand things over while I get some sleep.

The important thing to keep in mind is that this is driven off of a google sheets document as a backend and you don't want to push anything that might break that -- for instance you'll probably want to coordinate color palette changes with the folks updating the sheet.

**Comment by jdalt** [comment]
<a href="https://github.com/jdalt"><img src="https://avatars2.githubusercontent.com/u/2358067?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jdalt](https://github.com/jdalt)**
_Monday Jun 01, 2020 at 18:06 GMT_

----

I'd love to get some filtering in that side panel and tons of other usability improvements.

**Comment by jdalt** [comment]
<a href="https://github.com/jdalt"><img src="https://avatars2.githubusercontent.com/u/2358067?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jdalt](https://github.com/jdalt)**
_Monday Jun 01, 2020 at 18:08 GMT_

----

I would also imagine that google sheet + map is probably something that would useful to folks in other places.

**Comment by jdalt** [comment]
<a href="https://github.com/comeoneileen"><img src="https://avatars0.githubusercontent.com/u/2829021?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [comeoneileen](https://github.com/comeoneileen)**
_Monday Jun 01, 2020 at 18:10 GMT_

----

Hi. Yes. I also helped get this going and also haven't slept since...sometime yesterday morning but I'm around for a while as well. Yes, we definitely need help. Thank you for being here!

**Comment by jdalt** [comment]
<a href="https://github.com/maxine"><img src="https://avatars3.githubusercontent.com/u/23054741?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [maxine](https://github.com/maxine)**
_Monday Jun 01, 2020 at 18:11 GMT_

----

@jdalt made a [template Google sheet](https://docs.google.com/spreadsheets/d/1IIDsFN-If0IfNrRO-I3WbisHAz7EGjJ8aviSboX_-z4/edit#gid=0) with examples. Lmk if you want me to add you as a contributor so you can update any formatting I missed / got incorrect. For using this template in other areas, I'll look into how many times one mapbox API key can be used/the best way to deploy this multiple times

**Comment by jdalt** [comment]
<a href="https://github.com/andyinabox"><img src="https://avatars1.githubusercontent.com/u/151084?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [andyinabox](https://github.com/andyinabox)**
_Monday Jun 01, 2020 at 18:13 GMT_

----

@jdalt yes add me as a contrib! happy to manage this while you get some rest... THANK YOU (and @comeoneileen) for getting this going!!!

**Comment by jdalt** [comment]
<a href="https://github.com/jdalt"><img src="https://avatars2.githubusercontent.com/u/2358067?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jdalt](https://github.com/jdalt)**
_Monday Jun 01, 2020 at 18:21 GMT_

----

@maxine @andyinabox You've been added as contributors. @comeoneileen is already one as well as my partner @estherrose046 and a couple other folks I've invited (trying to get a couple people from my place of work to keep an eye things too).

I've reached out to the mapbox folks to try and get a bump in map capacity, but I think we should be good for now.

**Comment by jdalt** [comment]
<a href="https://github.com/mc-funk"><img src="https://avatars2.githubusercontent.com/u/10001418?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mc-funk](https://github.com/mc-funk)**
_Monday Jun 01, 2020 at 18:23 GMT_

----

@jdalt @maxine should I add the lat-long script to the spreadsheet example? 
Also I can link a gist with the scripts and the demo spreadsheet in the readme and submit a PR for that

**Comment by jdalt** [comment]
<a href="https://github.com/hinzed1127"><img src="https://avatars0.githubusercontent.com/u/13280995?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hinzed1127](https://github.com/hinzed1127)**
_Monday Jun 01, 2020 at 18:40 GMT_

----

hey y'all, another Minneapolis web developer looking to help 👋  

I don't want to duplicate work, but let me know where I can jump in. could be helpful to have some kind of messaging channel, as info for a lot of these orgs and their various needs is changing so quickly.

**Comment by jdalt** [comment]
<a href="https://github.com/andyinabox"><img src="https://avatars1.githubusercontent.com/u/151084?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [andyinabox](https://github.com/andyinabox)**
_Monday Jun 01, 2020 at 18:48 GMT_

----

> could be helpful to have some kind of messaging channel, as info for a lot of these orgs and their various needs is changing so quickly.

yes! i was just thinking that

**Comment by jdalt** [comment]
<a href="https://github.com/maxine"><img src="https://avatars3.githubusercontent.com/u/23054741?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [maxine](https://github.com/maxine)**
_Monday Jun 01, 2020 at 18:54 GMT_

----

@jdalt @comeoneileen is it ok with you if I set up a Slack channel for this? Or is there some other way you'd prefer to communicate?

**Comment by jdalt** [comment]
<a href="https://github.com/samanpwbb"><img src="https://avatars0.githubusercontent.com/u/108094?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [samanpwbb](https://github.com/samanpwbb)**
_Monday Jun 01, 2020 at 18:59 GMT_

----

👋  I've been looking for ways to help out as well – am a generalist engineer/designer with a lot of experience with maps :) – if there's a slack channel going I'd love an invite.

**Comment by jdalt** [comment]
<a href="https://github.com/jdalt"><img src="https://avatars2.githubusercontent.com/u/2358067?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jdalt](https://github.com/jdalt)**
_Monday Jun 01, 2020 at 19:07 GMT_

----

@maxine I'd welcome a slack channel. We might also be able to use one of the existing public groups like msptech.slack.com.

**Comment by jdalt** [comment]
<a href="https://github.com/mc-funk"><img src="https://avatars2.githubusercontent.com/u/10001418?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mc-funk](https://github.com/mc-funk)**
_Monday Jun 01, 2020 at 19:17 GMT_

----

@jdalt maybe Open Twin Cities since it's in the civic hacking space?

**Comment by jdalt** [comment]
<a href="https://github.com/maxine"><img src="https://avatars3.githubusercontent.com/u/23054741?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [maxine](https://github.com/maxine)**
_Monday Jun 01, 2020 at 19:35 GMT_

----

@jdalt @mc-funk @samanpwbb @comeoneileen @hinzed1127 @andyinabox just made a slack channel called `#proj-aid-locations-map` in Open Twin Cities (just joined their Slack from [their website](http://www.opentwincities.org/))

**Comment by jdalt** [comment]
<a href="https://github.com/jasonthibeault"><img src="https://avatars2.githubusercontent.com/u/6886202?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jasonthibeault](https://github.com/jasonthibeault)**
_Tuesday Jun 02, 2020 at 00:00 GMT_

----

Hey folks, @comeoneileen suggested I could help out, and I'm more than willing, internet connection allowing (I'm very rural right now). Going to join the Slack channel ASAP.

**Comment by jdalt** [comment]
<a href="https://github.com/experimatt"><img src="https://avatars0.githubusercontent.com/u/2946681?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [experimatt](https://github.com/experimatt)**
_Tuesday Jun 02, 2020 at 02:40 GMT_

----

Hi friends! I'm in to help, too!

**Comment by jdalt** [comment]
<a href="https://github.com/gabe-bergstrom"><img src="https://avatars1.githubusercontent.com/u/51203780?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gabe-bergstrom](https://github.com/gabe-bergstrom)**
_Tuesday Jun 02, 2020 at 03:26 GMT_

----

I'm also here to help!

**Comment by kmarekspartz** [comment]
I think this can be resolved as part of #43
