### ISSUE TITLE
Move Google Analytics property to the correct account

### ISSUE THREAD

**Issue by experimatt** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#101]
Google Analytics got setup initially under the wrong "account", and it should be an easy fix to move it to a completely separate new one specifically for Twin Cities Mutual Aid.

I believe Jason needs to make this change as he has admin access to the current GA property.

**Comment by mc-funk** [comment]
support@tcmap.org is now an Actual Email Address, FWIW. I don't think we can get any more accounts without paying Cash Money though.

**Comment by experimatt** [comment]
https://support.google.com/analytics/answer/6370521?hl=en

**Comment by experimatt** [comment]
@mc-funk "accounts" in Google Analytics" are different than G Suite accounts, but I think it makes sense for a support@tcmap.org email to be the _owner_ of the GA account. If you can set that up to facilitate the switch, that would be fabulous.

Also, docs on moving GA properties across GA accounts: https://support.google.com/analytics/answer/6370521?hl=en

**Comment by jasonthibeault** [comment]
@mc-funk @experimatt The destination account needs to have signed in with Google Analytics at least once -- so, if the owner of support@tcmap.org could log into that gmail account, then go here https://analytics.google.com/analytics/web/ and sign up for an account, that would be the first step. The second would then be me moving it to that analytics account. 

Sorry for having made it on my personal account -- it doesn't hurt anything, and the page views will still be collected, but if people are bothered by my personal vanity domain being property #1 (and the one that shows up on the invitation), I can understand completely

**Comment by experimatt** [comment]
@jasonthibeault I think we should add Michelle, Dallas, Esther, and the rest of the team to GA as soon as possible. I think Dallas' mind will be blown by the data and being able to see it in real-time

**Comment by jasonthibeault** [comment]
Added the three mentioned, plus Eileen; and I will be participating in a Zoom call at 12:30 to try to get the prerequisites set up on the destination account.

**Comment by experimatt** [comment]
@jasonthibeault awesome, thank you! Just looking at the real-time data right now is super encouraging

**Comment by experimatt** [comment]
This is done
