### ISSUE TITLE
Translate moment.js '8 hours ago' strings

### ISSUE THREAD

**Issue by caseyhelbling** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#108]
In one of the slack channels somebody mentioned this could be done... 

![2020-06-05 at 6 18 PM](https://user-images.githubusercontent.com/12005/83929446-08d00580-a759-11ea-969b-6746eee90ad9.png)

**Comment by benjifs** [comment]
moment provides some translations if we import the locale but most of the languages in the spreadsheet aren't translated there. Not sure of other languages but in Spanish just doing text replacement with the time wouldn't work grammatically.

I'm looking into it though so might have more info later

**Comment by andyinabox** [comment]
@benjifs moment.js has support for defining your own locales: https://momentjs.com/docs/#/i18n/. The `time_` terms I added to the translation doc came straight from looking at their spec: https://momentjs.com/docs/#/customization/relative-time/. We can probably just add a method to `translator.js` that spits out the configuration object.

**Comment by benjifs** [comment]
@andyinabox I'm finishing up a PR related to this. I've created my own locale based on the current translations. I was a little worried about the grammar but the translations + google translate helped sort most of that out.
