### ISSUE TITLE
Consolidated list of needs

### ISSUE THREAD

**Issue by jdalt** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#11]
<a href="https://github.com/andyinabox"><img src="https://avatars1.githubusercontent.com/u/151084?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [andyinabox](https://github.com/andyinabox)**
_Monday Jun 01, 2020 at 17:38 GMT_
_Originally opened as https://github.com/jdalt/twin-cities-aid-distribution-locations/issues/5_

----

Data is might be too messy for this but would be pretty helpful.

**Comment by jdalt** [comment]
<a href="https://github.com/comeoneileen"><img src="https://avatars0.githubusercontent.com/u/2829021?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [comeoneileen](https://github.com/comeoneileen)**
_Monday Jun 01, 2020 at 18:12 GMT_

----

Agreed with pretty helpful, especially to make sure that people aren't missing requests for Tylenol because the person entering wrote Tylanol (...has happened today), but yes, so messy.

**Comment by jdalt** [comment]
<a href="https://github.com/jdalt"><img src="https://avatars2.githubusercontent.com/u/2358067?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jdalt](https://github.com/jdalt)**
_Tuesday Jun 02, 2020 at 06:47 GMT_

----

I wonder if this is something to think about at the google sheets layer of things. It's sort of a "backend" and data modeling concern.

We could probably aggregate between sheets. I also wonder what sort of data sanitization tricks are available in sheets.

**Comment by jdalt** [comment]
<a href="https://github.com/andyinabox"><img src="https://avatars1.githubusercontent.com/u/151084?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [andyinabox](https://github.com/andyinabox)**
_Tuesday Jun 02, 2020 at 13:32 GMT_

----

I agree, in the meantime I've been trying to think of ways to do this with what we've got. Here are my thoughts on how a rough implementation with the data we have would look like:

1. Create a map of synonyms or common misspellings (this could be done with google sheets) to help consolidate terms. Example in JSON format:

```json
{
  "advil" : "ibuprofin",
  "tylonol" : "tylenol"
}
```
2. Break up the "Accepting" and "Urgent Need" into individual tokens by splitting apart at commas
3. Create a map of weighted terms, adding to the weight each time a term is found. Items from "Accepting" are given a weight of 1, items from "Urgent Need" are given a weight of 1.5. Something like this:

```json
{
  "ibuprofin" : 6.5,
  "tylenol" : 5
}
```
4. Display only items that have a weight of 2+ (this will reduce noise, and also hopefully help filter out some messy data). A simple word cloud would probably work for this, with word size based on the weight.

I was also thinking this could actually just be a separate page that we could easily send to people hoping to donate, so they have a sense of what's needed...

**Comment by jasonthibeault** [comment]
(There are also some tricks that can be done at Sheets with a macro that would enforce synonyms / common typos if actually manually checking the data entered is too cumbersome, but I worry about too much automation destroying the data on intake.)

**Comment by jasonthibeault** [comment]
I think if we focus on having the current pins' metadata be searchable via a box that filters as you type, that's probably all we REALLY need here -- we don't control the data (or macros to transform it) so it might be difficult for us to actually have any impact on that side of things

**Comment by jdalt** [comment]
> I think if we focus on having the current pins' metadata be searchable via a box that filters as you type, that's probably all we REALLY need her

That. Full text search over relevant fields for each site. Has a bit of ux trickiness because the location side bar would be filtered by things that aren't visible in the cards.

**Comment by jdalt** [comment]
Closing in favor of https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/issues/42
