### ISSUE TITLE
Make it easier to find and pick up things

### ISSUE THREAD

**Issue by kmarekspartz** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#112]
The map currently supports donors giving things fairly well, and #42 will make that use case much easier. Site organizers seem well supported behind the scenes. We may want to think a bit more about how to better support recipients getting items. Here's a few ideas I've seen floating:

- #42 but for items locations already have rather than donations
- restrictions on distribution ("some sites open for distribution but only to specific groups of people")
- Opening modal: "ask if the user is looking for specific things like volunteering, specific items to donate/pick up, and then apply filters based on their answers"
- request items that may not be listed at any open site (!) (may be related to #12, though that's more for site organizers)

Already open issues that should help recipients:
- Design improvements: #99, #2, #80
- Tracking COVID precautions: #63
- Translation improvements: #108, + more translations in flight

One thing to keep in mind is that people may be both a donor and recipient, I'd rather not split the UI into two totally separate usecases if possible.

**Comment by drewsteff** [comment]
I think we need to decide the specific filters or things we want to include on these options first and then continue into how that is implemented onto the site. Definitely doesn't need to be two UI screens but could be good to make sure we have the needs of each type of user listed out to then incorporate onto the site as features. 

For example if we're looking at how to best serve the user who is someone that needs to receive items for children and baby formula, what are the categories they would want to filter or help specify their search? Are there decided categories and/or specific labels to identify these needs that can be selected such as 'distributing food' or 'distributing items for children and youth' or something like that. We essentially will just need to agree upon the terms that would be sorted or categorized.

I like the idea of having ways that the recipients can find their specific needs through some sort of labeling or categorization.

**Comment by estherrose046** [comment]
Closed in reference to #194
