### ISSUE TITLE
Combine open & closing times into one "hours" list item in map markers

### ISSUE THREAD

**Issue by experimatt** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#122]
This is something that has felt off to me but I haven't created an issue for it until now.

Right now, there are separate list items for each of opening/closing times for both _receiving_ AND _distributing_ donations in the location marker popup. i.e. there are separate list items in the popup for all four of these fields:

- Opening for receiving donations
- Closing for receiving donations
- Opening for distributing donations
- Closing for distributing donations

This takes up a lot of space, and I think we can combine these four fields into two to make it easier to read at a glance. I'd love to replace each of the opening/closing fields into one "hours" field, like so:
- Hours for receiving donations
- Hours for distributing donations

Screenshots of what we're currently doing below for reference:

<img width="269" alt="Screen Shot 2020-06-06 at 1 47 23 PM" src="https://user-images.githubusercontent.com/2946681/83952391-433fae00-a7fe-11ea-84b1-80d0cf42adc8.png">

<img width="265" alt="Screen Shot 2020-06-06 at 1 47 33 PM" src="https://user-images.githubusercontent.com/2946681/83952393-4470db00-a7fe-11ea-87b3-cce636596834.png">

**Comment by experimatt** [comment]
@estherrose046 I'd love your input on this one :)

**Comment by jdalt** [comment]
@experimatt Any idea how this might interact with sites that are effectively never open for receiving or distributing donations - that are really just there for receiving monetary donations? I think it's *mostly* a separate issue, but I suppose this is a fact about their hours that warrants communication.

**Comment by estherrose046** [comment]
@experimatt this is a great idea! 

@jdalt Currently when sites are "never" open for distributing, we handle it by typing "never" into the "open for distributing" column. Ditto for never open for accepting donations. 

When sites aren't going to be open at all today,  we type "not today" in the "open for distributing" column and again same for open for receiving. 

I think with Matt's solution,  that means that we'll see this:

Hours for distributing donations: never

we could parse that into something like "not a distribution site" 

And similarly we would see something like this:

Hours for distributing donations:  not today

And maybe. we would want to parse that into "not open for distributing today"

Definitely love the idea of consolidating that, less clutter!!

**Comment by experimatt** [comment]
Yeah I think there are larger data viz opportunities here because those "never" fields are really just booleans. We could probably combine a number of them into a field to the effect of "Services available at this location" i.e. donation drop off, donation pick up, volunteering, etc...

But I don't want to overcomplicate starting with combining hours into one field instead of multiple.

**Comment by experimatt** [comment]
@estherrose046 you're also alluding to a bigger picture problem/solution, which would be scheduled hours for a week. Considering all of these locations are less than a week old, we don't know what future, predictable hours and schedules will look like yet, but I'm sure this will start to bubble up in importance over time.

**Comment by estherrose046** [comment]
@experimatt true that - hoping that this project remains active into the future, when we see site hours stabilizing more and can report ahead of time with more accuracy!!
