### ISSUE TITLE
Make the language selection modal scrollable

### ISSUE THREAD

**Issue by experimatt** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#123]
The language list is too long and isn't scrollable, which presents a problem on small screens.

Reported by @mc-funk.

<img width="345" alt="Screen Shot 2020-06-06 at 2 06 59 PM" src="https://user-images.githubusercontent.com/2946681/83952521-01633780-a7ff-11ea-8fbc-ecedd9e46e3e.png">

**Comment by jdalt** [comment]
The translations effort has become so successful that it's created a problem. Huzzah!

**Comment by crhistianramirez** [comment]
I can look into this unless you already are @jdalt ?

**Comment by jdalt** [comment]
@crhistianramirez go for it. I'm really just performing an administrative support function right now.
