### ISSUE TITLE
Add search field that allows users to narrow down visible sites by arbitrary string

### ISSUE THREAD

**Issue by mc-funk** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#127]
This is an incremental step on the path to #42 . 

We would like to place a search box, "Search aid sites".  When the user enters any arbitrary string, the only map points and side list items that appear will be ones whose data fields include that string. 
I think this is most non-boolean fields, such as receiving donations, distributing, site title, volunteers, and so forth.  We might also want to include the address since people may want to filter by their zip code or a street name. 

It will need a 'clear' button to make it easier to clear any undesired map states. 

We will also want a hover state to prompt what the user can enter, e.g. 
`Type here to narrow down the aid sites you see. Examples: "food", "church", "55413", "St. Paul", "bilingual"` -- this is important but likely not blocking an initial feature merge. I think it is important enough that getting translations for it shouldn't be a barrier, since that will be blocked on a process to get translation updates that I"m not suer is in place. 

@drewsteff is working on some guidance on search box placement now.

**Comment by crhistianramirez** [comment]
I can take a crack at the logic side of things

**Comment by drewsteff** [comment]
<img width="1678" alt="Search   Filter - Inactive Button state" src="https://user-images.githubusercontent.com/66445081/83956132-3b910100-a820-11ea-8913-995b312a1ab6.png">
<img width="1678" alt="Search   Filter - Active Button State" src="https://user-images.githubusercontent.com/66445081/83956133-3e8bf180-a820-11ea-9973-ff0ec017718b.png">
<img width="1678" alt="Search   Filter - Help Pop Up Window" src="https://user-images.githubusercontent.com/66445081/83956134-40ee4b80-a820-11ea-80fa-d423265cbc62.png">

Passed these along to @crhistianramirez with the Figma link. I can post the link here too if anyone's interested in grabbing the CSS from it

**Comment by andyinabox** [comment]
@drewsteff do you have mockups for small screens? Last I heard we had twice as many mobile users as desktop. I'm worried this might take up too much screen space on a phone...

**Comment by drewsteff** [comment]
@andyinabox Let me resize

**Comment by andyinabox** [comment]
@crhistianramirez the library we're using for the filtering is https://listjs.com/, which has some fuzzy search capability. I'm not at all attached to it, but might be worth looking into that first...

**Comment by drewsteff** [comment]
Let me know if this makes sense @andyinabox 
<img width="376" alt="Mobile View Search - Inactive Buttons" src="https://user-images.githubusercontent.com/66445081/83956949-c4ac3600-a828-11ea-8570-71751a39ed4c.png">
<img width="376" alt="Mobile View Search - Active Buttons" src="https://user-images.githubusercontent.com/66445081/83956953-c70e9000-a828-11ea-806f-8834e4efce5b.png">
<img width="376" alt="Mobile View Search - Help Pop Up Window" src="https://user-images.githubusercontent.com/66445081/83956955-cbd34400-a828-11ea-9ec5-1c8a301451dd.png">

**Comment by crhistianramirez** [comment]
@andyinabox  roger that, i'll swap out libraries, shouldn't be a big deal. Less libraries is less complexity so i'm on board with that

**Comment by crhistianramirez** [comment]
On second thought I'm seeing lunr is a lot more full-featured in terms of search providing things like indexing, ranking, and natural language stemming. We might not use that right away but it would be nice to tap into in future iterations. Given how important search is I think it might make sense to use that instead. Any strong opinions on that?

**Comment by andyinabox** [comment]
@crhistianramirez yeah go with what you think will work best, just thought you might want to check out what already there. List.js has gotten us this far but it's nothing special.

@drewsteff awesome thanks for whipping up those mobile mockups! i wonder if it might be possible to slim the search down the vertical space a little bit? some things that come to my mind: 
 - maybe "Need help or search examples?" could go under the "Help/Info" section
 - it seems like we might be able to find a way to keep the search field & buttons on the same line. for instance, instead of a "clear search" button maybe something like this:
![Screenshot from 2020-06-06 20-34-16](https://user-images.githubusercontent.com/151084/83958256-4efa9700-a835-11ea-9af6-9f1265c9437f.png)
 - is the "OR" necessary?

would be interested to see what other people think ... i know up until now we've put a lot of attention toward cutting down the vertical space of the nav

**Comment by crhistianramirez** [comment]
> is the "OR" necessary?

Yeah, I don't think its an either/or thing. Shouldn't you be able to sort your search results?

**Comment by drewsteff** [comment]
Only thing with the search placeholder text is that screen readers don't read those. We should be aiming for full accessibility compliance especially with the populations we're working with

**Comment by drewsteff** [comment]
I'm creating a second mock up I'll post in a few mins

**Comment by drewsteff** [comment]
Possible second option
<img width="1678" alt="Frame 3 (1)" src="https://user-images.githubusercontent.com/66445081/83959732-35158000-a846-11ea-9aaa-601f5a2e3901.png">

**Comment by crhistianramirez** [comment]
Is anybody available to take this over the finish line? I got the search functionality piece complete and the only thing left is to add the help modal, unfortunately I won't have time to work on this until later this afternoon and I'd hate for it to be held up until then.

Here's my branch https://github.com/crhistianramirez/twin-cities-aid-distribution-locations/tree/new-search

**Comment by mc-funk** [comment]
@crhistianramirez Sorry I didn't see this! I will check in on where this was in the slack and we will see if we can get it over 🏁

**Comment by crhistianramirez** [comment]
Actually I should have updated this issue. It looks like Lanie (from slack) is going to take a look at it :)

**Comment by mc-funk** [comment]
Added in #156!
