### ISSUE TITLE
Improve Organization of our Translations Effort

### ISSUE THREAD

**Issue by jdalt** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#131]
I’d like to improve the organization of our translation effort. Right now it’s not clear how to add new languages or add keys to existing languages.

Here’s the steps that I think would make it better:
- [x] create a #tc-aid-translations Slack channel
- [x] document how to add a new language to our translations
- [x] document how to add new translation keys for existing languages
- [x] add a needs-translations tag to the repo/project
- [x] have some loose idea of who to direct questions to (maybe the Slack the channel would be good enough)

**Comment by cwood821** [comment]
Related #106

**Comment by experimatt** [comment]
Per https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/pull/133, this is done, but there's a follow up task per the thread in that PR, to move the static translation data from the google sheet to a version controlled file within the repo. I'll create a separate issue for that and reference this one.

**Comment by experimatt** [comment]
New Issue for moving translations from google sheets to something version controlled: https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/issues/145
