### ISSUE TITLE
Better way to handle sharing .env settings with developers

### ISSUE THREAD

**Issue by andyinabox** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#135]
I think it's hard to keep track of things like ENV variables in slack, so it would be nice to have a place that's available to org members but no the public.

 I set up a private repo here as a possible way to handle this: 

https://github.com/Twin-Cities-Mutual-Aid/secrets

Didn't populate it yet though so people can weigh in on whether this is a good strategy. Generally I wouldn't put ENV vars in a repo, but I thought it might be ok in this case.

**Comment by experimatt** [comment]
@andyinabox I think this is a great idea, and "good enough for now" strategy. Alternatively we could just create a private gist, that you could only see if you're a member of the org? Don't know if we need a whole repo for secrets

**Comment by benjifs** [comment]
I've never tried this before so not sure if this is a good solution in terms of who can access it but under `settings` > `secrets` for this repo we are able to store keys that are only shown to collaborators. I like the idea of a private repo or gist as an alternative.

**Comment by experimatt** [comment]
@benjifs Oh dang, that feels like it was designed specifically to solve this problem.

+1 I think we should do that if possible.

Here's a link to the settings page https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/settings/secrets

**Comment by andyinabox** [comment]
@experimatt yeah I thought about a gist, but this:

> Secret gists aren't private. If you send the URL of a secret gist to a friend, they'll be able to see it. However, if someone you don't know discovers the URL, they'll also be able to see your gist. If you need to keep your code away from prying eyes, you may want to create a private repository instead.

@benjifs didn't know about that feature, pretty cool! Just tried it out and it encrypts the values, so they aren't visible ... which doesn't really work for our use case. I think it's more for incorporating into automation tasks? :shrug: 

I'll put the ENV variables in the private repo for now.

**Comment by benjifs** [comment]
@andyinabox that would've been great if it works. Private repo for now works.

Should we also set this up on Slack so that it updates the #dev channel when there are changes in the secret repo?

**Comment by experimatt** [comment]
@andyinabox I just used the secrets repo to populate my local `.env` file and it worked great. Nicely done! 🙌
