### ISSUE TITLE
Integrate automated end to end tests with CI/CD

### ISSUE THREAD

**Issue by crhistianramirez** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#142]
[This PR](https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/pull/140) recently added end to end tests. Currently, these tests need to be run locally (manually). It would be better if they ran automatically.

Considerations:
- These tests should run on every new pull request (and probably again anytime the PR changes)
- Would be ideal if it worked with Netlify although [it seems that might not be possible](https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/issues/105#issuecomment-640265940) next best would be  [Gitlab CI](https://about.gitlab.com/solutions/github/) or [CircleCI](https://circleci.com/open-source/)

**Comment by jdalt** [comment]
I think [TravisCI](https://travis-ci.org/)  is free for open source projects.

**Comment by benjifs** [comment]
I just added some additional tests and submitted PR #143

I also ran TravisCI on my branch with all the tests and it worked pretty well so it should be fairly straightforward to setup.

https://travis-ci.org/github/benjifs/twin-cities-aid-distribution-locations/builds/695935214

**Comment by jdalt** [comment]
@benjifs Thank you. This warms my heart.
