### ISSUE TITLE
Move translations to version controlled files in the repo

### ISSUE THREAD

**Issue by experimatt** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#145]
We originally started with a google sheet for translations, and now that we've got a better understanding of how that process and implementation works, we've got consensus around moving the translations from google sheets to version controlled files within the repo.

Implementation details and/or which specific frameworks to use are yet to be determined, so this issue encompasses doing the research to figure out how best to accommodate this.

Please read the discussion in https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/pull/133 (starting with https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/pull/133#issuecomment-640257514) for reference.

**Comment by experimatt** [comment]
@andyinabox @jdalt @caseyhelbling let's use this issue for further discussion

**Comment by amaxama** [comment]
Closing as issue was completed by PR #167
