### ISSUE TITLE
Improved labels/color contrast on needs listed for locations (seeking volunteers, seeking donations, etc.)

### ISSUE THREAD

**Issue by drewsteff** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#148]
Please change the text on the small labels on each location in the list location view to not have red text on red background - for example:

![Screen Shot 2020-06-08 at 7 28 55 PM](https://user-images.githubusercontent.com/66445081/84092877-4e413c80-a9be-11ea-9009-106af0509300.png)

This should really be changed to have the text color as #000000 and then it's passing accessibility requirements. Boom

(example of change below)
<img width="133" alt="Improved label" src="https://user-images.githubusercontent.com/66445081/84093706-92354100-a9c0-11ea-958d-593a0c31287a.png">

**Comment by amaxama** [comment]
@drewsteff The color update was made as part of #150 , is that what was needed to fulfill this issue? In the example you gave above it looks like the text is also bold, is that needed for the accessibility requirements as well or the non-bold text that's currently on the chips works?

Are there other color contrast issues that need to be fixed to improve accessibility? Not sure if there's a tool you're using but this is a tool that a few other devs and I used a couple days ago when we were adding a new feature: https://webaim.org/resources/contrastchecker/

**Comment by drewsteff** [comment]
Howdy - the text is not required to be bold no.

I've been using two tools on Figma when I'm macking wireframes or designs - Stark and A11Y contrast checker. Here's a screenshot below of them both:

<img width="1310" alt="Screen Shot 2020-06-09 at 6 27 28 AM" src="https://user-images.githubusercontent.com/66445081/84143255-ddc90880-aa1b-11ea-8431-5a445c10cc23.png">
<img width="914" alt="Screen Shot 2020-06-09 at 6 27 54 AM" src="https://user-images.githubusercontent.com/66445081/84143260-e02b6280-aa1b-11ea-9ca4-8de61043c99d.png">

I also added the WAVE chrome extension and tested the site and here's a screenshot showing how it's looking so far with the page tested initially. I would need to dig in more but I can help work on any contrast issues as a start.

<img width="1279" alt="Screen Shot 2020-06-09 at 6 39 43 AM" src="https://user-images.githubusercontent.com/66445081/84143849-e5d57800-aa1c-11ea-9410-746b94947dd4.png">

**Comment by estherrose046** [comment]
This issue was addressed in https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/pull/150, closing this issue
