### ISSUE TITLE
Prompt user to reload the page if there's trouble fetching

### ISSUE THREAD

**Issue by alexives** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#155]
Right now, if the sheets data or translations fail to fetch, the map just shows up blank. I'd suggest we find a way to make sure we show an error modal if something goes wrong.

Like, throw up a modal with a button to refresh the page with a message like "Oops! Looks like something went wrong, please try reloading the page!"

We should also improve our handling when a fetch fails, but that can be a separate issue.

### Acceptance Criteria
- [ ] If a fetch fails, a modal displays
- [ ] TrackJS events are still logged when a fetch fails.

**Comment by jdalt** [comment]
We could also retry the fetch a couple times first.

**Comment by alexives** [comment]
I think we should do both!

**Comment by cwattrus** [comment]
Mocked up a design for how this could look. Let me know if there's feedback or anything else you'd like to see:
<img width="1440" alt="RefreshToFixTCMAP" src="https://user-images.githubusercontent.com/136817/85955575-1423e480-b945-11ea-9fe7-ff190ea40cba.png">

[Figma design](https://www.figma.com/file/THWSVdpnb0IgtT831ba4iW/Twin-Cities-Mutual-TCMap?node-id=16%3A405)

**Comment by lbarhaugh** [comment]
The solution proposed for this is in TC Map Slack is just to have a "Refresh" or "Reload" button that a user can click whenever, *not* something that prompts after an error. https://tcmap.slack.com/archives/C014VT6ETUJ/p1593891321368600

**Comment by amaxama** [comment]
Closing as have not seen this be a continued issue and backend will now return cached data if there's an error fetching. Will still be accessible in the issues!
