### ISSUE TITLE
Tweak search functionality on aid map to allow Google Analytics to pick up search terms

### ISSUE THREAD

**Issue by echoseekererer** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#158]
Currently there is no way for GA to track what users are searching for in the new search feature.
OOTB GA functionality relies on URL query parameters passing search terms and filters, which doesn't seem like an option here.
Can we get a global variable to pass search terms in the current set up? Or other options that Tag Manager can grab?

**Comment by echoseekererer** [comment]
@crhistianramirez quick and easy, awesome :)
Will you be doing just the search terms or the map filters as well?

**Comment by crhistianramirez** [comment]
Yep, filters too

**Comment by crhistianramirez** [comment]
@echoseekererer I got search done but I won't have time to finish query parameters for filters tonight. I'll make a pull request for search today and continue tomorrow

**Comment by echoseekererer** [comment]
@crhistianramirez This needs the global variable approach or a page re-load trigger when users complete a search/change a filter (not ideal imho). Or something else I'm missing all together, maybe :)

I've added and tested the OOTB GA implementation for this as-is, and since the search functionality doesn't currently trigger a page re-load, GA will not pick up the search term when users are routinely searching. The same will be the case with filter variables if implemented the same way. GA's OOTB tracking is basically built for a search page scenario, not something as dynamic as this, so we have to be a bit sneakier, I think.

That said... the current setup (using the query params w/o page re-load) *will* let us know if users are sharing or bookmarking these tailored links, which is info that's pretty much impossible to get otherwise. Not ideal by itself as far as search tracking goes, but paired with a global variable for GTM to pick up, I think we can get some really powerful data here.

**Comment by crhistianramirez** [comment]
Ah, I was actually wondering that. Yeah, I agree a full page reload isn't ideal. 

I can look into it this evening. I'm not super familiar with GA but I'm sure it shouldn't be too difficult

**Comment by echoseekererer** [comment]
Yeah, my bad. I should have more clearly articulated my doubts at the outset. Not a complete loss, though! Thanks for your work on this.

**Comment by jdalt** [comment]
At the day job. Can help later. I think the relevant information for getting GA to trigger correctly is here: https://developers.google.com/analytics/devguides/collection/analyticsjs/single-page-applications

**Comment by echoseekererer** [comment]
@crhistianramirez @jdalt are we still working on getting event tracking for the site filters? Ideally they would pass:

Event Category: Search Filter
Event Action: Select
Event Label: <filter label>

List Sort would be cool, too, but those checkbox filters are more of a priority so we can start getting a handle on how many users are looking to drop off vs pick up.

Tags like this are ones I can typically add quickly in Tag Manager if we have a container set up. Not clear on that, sorry, having trouble following all the references here! I’m in transit for most of tomorrow, so I want to make sure you have what you need from me on this.

**Comment by crhistianramirez** [comment]
@echoseekererer yes, I can work on adding this tonight. I see [this pull request](https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/pull/166) should have added tracking for search. Can you confirm you're seeing that in analytics now?

**Comment by echoseekererer** [comment]
Yes, seeing both of these options in GA.
