### ISSUE TITLE
Change "currently closed" text to read "not open now" 

### ISSUE THREAD

**Issue by mc-funk** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#162]
We have had reports of confusion around the label for red pins being "currently closed" since people have inferred more permanence from it. 

After a few discussions on the TCMAP side we agreed that "not open now" was adequately clarifying, and that the difference wasn't significant enough to need an immediate reevaluation of translations etc.

**Comment by experimatt** [comment]
@mc-funk this is a simple _code_ change, but we'll need to get translations for "Not open now" in all of the languages in the spreadsheet 😬

**Comment by mc-funk** [comment]
@experimatt yeah, I meant to be clear that we think that it's worthwhile enough to improve the English issue for now while making sure we are keeping track of the possibility that we'd need to improve translations too. Since we don't have a process for updating translations and we're working on that. 

Also, we're not sure the translations share the ambiguity of the English in the first place -- so yeah, it's a future concern for translators to evaluate for sure

**Comment by experimatt** [comment]
@mc-funk I just changed "currently closed" to "not open now" in the translation doc, and so that change is live in prod right now.

I'll also open a PR to update the hard-coded default text

**Comment by experimatt** [comment]
@mc-funk very small PR ready for your review :) https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/pull/163

**Comment by experimatt** [comment]
The initial fix of changing the wording of the English version is done! See https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/issues/164 for follow-up work to translate the wording change to other languages
