### ISSUE TITLE
Time-based filter or sort

### ISSUE THREAD

**Issue by lbarhaugh** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#165]
We have a request to sort by “most recently updated”. 

This could be either:

1. a sort drop-down option of "Most recently updated"
2. a filter radio button of "updated in the last X hours" 

UX folks - is one of these better from a user perspective?
Dev folks - is one of these more feasible from a code perspective?

**Comment by drewsteff** [comment]
Personal thought from UX perspective: 

If it has a sort by option labeled 'Recently Updated' that should be enough to convey the purpose and would more be a matter of how we are pulling that info to sort from a developer standpoint.
