### ISSUE TITLE
Data modeling for new back-end

### ISSUE THREAD

**Issue by experimatt** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#171]
This is a big picture/research task related to moving away from Google Sheets (Issue https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/issues/157).

You'll want to refer to the [PUBLIC](https://docs.google.com/spreadsheets/d/1CyPozeKhmOuIaVnKDQAUKKsvA9R4F20hEQ3MSGWczP8/edit#gid=0) version of the spreadsheet, and possibly the master version as well (it's locked down, so you'll need to request access, if necessary).

This will get big and overwhelming fast if we don't have a clear distinction between what is in and out of scope for an MVP version of the back-end.

**Comment by experimatt** [comment]
I just took a stab at it, and after a handful of iterations this is where I arrived: [TC Mutual Aid Map ERD DRAFT](http://erdraw.com/graphs/672115778226/edit). There are still a lot of open questions and this is very rough, but it's a start. Screenshot below.

![image](https://user-images.githubusercontent.com/2946681/84601220-495c0d00-ae44-11ea-9c18-a4f42c568802.png)

**Comment by experimatt** [comment]
@jdalt I'd love your input and perspective here

**Comment by comeoneileen** [comment]
I think this looks like a pretty good representation of the _public_ spreadsheet and some of the related issues you and @estherrose046 and @jdalt and I talked through on Friday. On the _private_ spreadsheet, though, there are columns for internal notes and for what our information source is for each site - and it would make sense for those to exist here too, right? Otherwise I think we'd have to still use Google sheets to track those things.

**Comment by experimatt** [comment]
@comeoneileen good catch. Depending on the back-end we end up using, there will likely be libraries we can pull in to allow commenting on _anything_ (as an example, ActiveAdmin has comments functionality built into it by default), which would allow multiple comments to be made by different people along with timestamps, as compared to a single "internal notes" field that would keep getting overwritten with the most recent information. There's merit to both solutions, but comments would be my recommendation, as I just went through the same thing at work.

Regardless of how we implement it, I can add the idea of comments to the ERD. That's no problem at all :)

**Comment by comeoneileen** [comment]
@experimatt That makes a lot of sense! As long as comments are easily visible (I haven't worked with ActiveAdmin) and difficult to dismiss by accident, sounds good - we tried using Google Sheets comments rather than a separate column at first, and they were difficult to see/we had a lot of issues with folks hitting "resolve" because they didn't realize that meant more than "stop showing me this box at this moment."

**Comment by experimatt** [comment]
oh yeah the idea of Comments vs what that "comments" means in Google sheets are totally different. The google sheets version isn't anywhere close to what we need or the experience I had in mind.

**Comment by comeoneileen** [comment]
That's what I figured - thanks for confirming!

**Comment by comeoneileen** [comment]
Here are two other data modeling headaches: some sites are open by appointment only, and it'd be groovy to have a way to show that. Also, some sites have split hours (open 10am-12pm and 1pm-4pm, eg).

**Comment by TimothyMDean** [comment]
New to this app, so my apologies if this is a dumb question, but here goes:

Is there any value in extracting the parent organization out to its own entity, perhaps allowing service need items to be associated with the organization? For example, if the YWCA were to set up distribution centers and multiple locations but want to report in a consolidated set of items they need across all their locations?

Not sure if that is a real use case, but seems like something that could happen.

**Comment by comeoneileen** [comment]
@TimothyMDean, sorry about missing your comment - that's a solid idea. I can certainly think of similar use cases we've encountered.

One other data modeling thought: as information has stopped flying at us a million miles an hour, the data "entry" role is transforming from a passive waiting for information to reach us into a more active sleuthing out updates, following up with contacts, and reaching out to organizations with websites that appear outdated, etc. We've also got more information streams than ever - most notably that we're on Instagram and Twitter as well as Facebook. **I'd like there to be a way to list who our contacts are for a site, how we communicate with them, when we last reached out, and when we last heard back.** Ideally, that could be turned into automated reminders/a daily list of places we haven't heard from in X number of days and should prioritize.

**Comment by comeoneileen** [comment]
Oh, and one of our biggest user needs right now is a way to answer the question, "What's not open NOW but will be at some point today?". That's probably not a data modeling concern, but I'm dropping it in here because I think this thread will be heavily referenced in hackathon-ing.

**Comment by amaxama** [comment]
Closing as is not currently relevant for airtable database. Lots of great thoughts here and could potentially re-open in future if we move to our own, fully relational db. Will still be accessible in closed issues!
