### ISSUE TITLE
Technical Evolution - Why We Need a Backend

### ISSUE THREAD

**Issue by jdalt** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#174]
To better serve our users and our Lizards, we need a richer way to create, update, and publish  data.

#### Background
Our backend is currently Google Sheets. It actually works pretty well. It’s perfect for hackathons. However we’re outgrowing it.

### Google Sheets Problems
1. Editing data in a massive single row is hard on the eyes and the brain.
2. The sheet is fragile - we’ve broke the public sheet several times. Migrations require down time.
3. Keeping certain data private to Lizards is tricky. The published Spread Sheet requires multiple import statements to handle gaps in the columns.
4. We want to model more things than we’re currently able to model - sites hours for each day of the week, services offered, a validated list items offered and accepted, and site contact information for internal use.
5. Providing self serve data updates by site operators/representatives would be difficult. It would probably require and fairly complex API shim do it in Sheets. The Twilio system gets us closer to self serve, but we could take that even further with a real backend.

These problems are a big deal and they limit what we can do to serve the community. For this reason we need a real backend.

However I also want us to take a moment to remember what Google Sheets provides a solution for:

### Google Sheets Solutions
1. Query API that scales (web server, caching)
2. Collaborative data editing (interface + database)
3. Authentication

These solutions are a big deal and any backend technology that can replace Sheets has to solve 1-3 at a high level of quality before we can even begin to solve for the problems. Notably we need a backend that can absorb a fairly large amount of traffic. We need backend that we can train a lot of volunteers on fairly fast.

In imagining our backend we also need to think about how we'll maintain it, where we'll host it, how we'll pay for that hosting, and how we'll teach and mentor new developers as we build it.

Any option needs to answer for what google sheets solves, the new problems that we want to solve, and the operational concerns of running it.

Not let's talk about our options.

**Comment by JamesMGreene** [comment]
I don't have firsthand experience with it but I've heard good things about using [Airtable]() as a [relational database](https://support.airtable.com/hc/en-us/articles/360021502354#h_0c3d1a65-1f35-4e67-9b14-6213d4d2bca9) with a [spreadsheet-like UI](https://airtable.com/product), an [API](https://airtable.com/api) with [Node and browser SDKs](https://www.npmjs.com/package/airtable), and [apps for Windows, Mac, iOS, and Android](https://airtable.com/downloads).

This project would probably also be fine with the [free plan](https://airtable.com/pricing) as far as I can tell (max 1200 records per database, unlimited databases), though they do at least [offer a 50% discount for Plus/Pro plans for nonprofits](https://airtable.com/shr9DxhP6lU9slZE6) if that is deemed necessary. 🤔  🤷‍♂️

**Comment by Jaszzz** [comment]
I wanted to throw out another option that I think is worth exploring. [Directus](https://directus.io/) is an open source headless CMS with both an admin interface and an API "out-of-the-box". The feature set that it comes with is very in-depth, and it supports multi-tenant user permissions with publishing restrictions (rare for an open-source headless CMS from my experience). Docs are [here](https://docs.directus.io/getting-started/introduction.html). It even supports adding custom field types and interfaces with a well thought-out methodology.

I spun up a small DigitalOcean Droplet, and created collections that replicate the current Google Sheet structure fairly well. Added 4 of the locations as examples. Details are below for anyone to review:

[Admin Interface Login](https://demo.jaszzz.com/admin)

Owned Location(s) Admin Credentials - This user role is set up to only be able to see and edit their own location(s), along with creating new locations.
- Email: single-location@user.com
- Password: gFNxBv4$OMYSyd25Yg

All Locations Admin Credentials - This user role is set up to be able to see and edit any location, along with creating new locations.
- Email: admin@user.com
- Password: gbDTF#bwZ60Tu28#hk

With the 4 locations that are currently added, an example API output from the RESTful API is [here](https://pastebin.com/MjEUQAJS).

I feel like this product is "fully-baked" enough to satisfy a lot of the basic requirements (security, user permissions, DB structure, RESTful API, etc.), but extensible enough to allow the project to customize as much as needed. I have some ideas related to hosting as well, but will need to detail those out tomorrow.

Interested to hear others' thoughts after looking at the docs + the example above.

**Comment by AndrewReitz** [comment]
I would like to suggest squarespace. https://www.squarespace.com/

It's the easiest way I know of to make a website, and uptime and hosting is all on them so we wouldn't have to worry about all of that. It's can be bit of a pain if you want to do very customized stuff, but I think it might work well for what we are looking to do.
