### ISSUE TITLE
Analytics: Add Outbound Link click event

### ISSUE THREAD

**Issue by echoseekererer** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#184]
I would like to track outbound link clicks to better understand how users are interacting with location content. This is not something GA tracks OOTB.

Event Category: Outbound Link
Event Action: Click
Event Label: [full link]

Ideally we would have link classes for common link types (EG: Volunteer Signup, Donations, Contact Location, etc) to fire off DOM click events, with metadata for the location passing with the click (EG: Site Name or ID). This approach categorizes a wide array of link destinations with minimal maintenance and greater accuracy on the analytics end. If that’s possible with the current spreadsheet authoring workflow, sweet! Events would be:

Event Category: [link class] Link
Event Action: Click
Event Label: [full link]

If not, something to flag for #171

**Comment by comeoneileen** [comment]
Dallas would really like to see this happen ASAP, especially for seeing how often folks are clicking on "Donate Now" links and using the map as a tool to make financial contributions rather than items - could it be bumped up in priority?

**Comment by echoseekererer** [comment]
Still unfamiliar with process here and GitHub ins-and-outs. If we have a GTM container set up, I can add and QA this one in ten minutes. Javascript here, not so familiar with.

**Comment by comeoneileen** [comment]
Blurgh, not a question I can answer...and I'm not even sure who could. @jasonthibeault set up GA to begin with - Jason, is this something you can help with?

**Comment by jasonthibeault** [comment]
Now that it's on its own GA account, with Tag Manager set up, as far as I know following these instructions is (mostly) all that needs to happen to perform click tracking. The big problem is, I'm out of date on how the links for the paypal etc are even being built, so I'm not sure if this is easily integrateable. 

https://support.google.com/analytics/answer/1136920?hl=en

**Comment by echoseekererer** [comment]
If we have a Tag Manager container set up, we can implement there and not have to worry about adding that link attribute.

**Comment by estherrose046** [comment]
We may still want to upgrade to using Tag Manager in the future, but for now this issue is resolved with https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/pull/209
