### ISSUE TITLE
Use cultural pattern for Hmong language instead of current flag 

### ISSUE THREAD

**Issue by mc-funk** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#186]
Replace currently used flag for the Hmong language to this image:
![2](https://user-images.githubusercontent.com/10001418/85135048-1084b500-b203-11ea-8fc2-2bf14120ac94.jpg)

One of our Hmong translators who is also a graphic designer offered up this flag art for us to use instead of what we currently have, with this lovely explanation of why it is more inclusive and recognizable to Hmong people. We discussed with TCMAP (including Chou Moua who confirmed this as recognizable) and made sure we got a 'flag' with the appropriate aspect ratio to work with the existing flags. 

>I have since seen the Twin Cities Aid website and it looks good and has lots of information.
> I wonder if you know how the image that is attached to “Hmong” came about? I do recognize the image as a flag used by some Hmong people, who would say that it is the flag of Hmong people, but I would also say that it might not be the first image I would use. While it may represent Hmong to some Hmong people, I am not sure if it is widely recognizable as such by Hmong people in Minnesota. 
> Please find attached an image that I composed in PhotoShop (I also dabble in graphic design). It is an image that comes from Hmong handicraft/textile work. I think the attached image might be more recognizable. It is not an image of a flag of a nation, but instead a widely seen popular design used in many Hmong handicraft textiles. I would suggest using this image rather than the red flag that is currently on the site.
> I just wanted to share quick simple background info on Hmong people living in Minnesota.
> There is no country called Hmong, as Hmong people now come from a variety of countries around the world. As such, there is no one flag that represents us all; there is no single country of origin.
> It is said that Hmong people lived in China for many many years, where we may be known by the name “Miao”, one of over 50 ethnic minorities recognized by the Chinese government. Over time, war and efforts by other groups to expand territories lead to many groups being displaced, including the Hmong. As such, Hmong people were pushed further south into Southeast Asia leading to many Hmong living in what we know today to be the countries of Laos, Viet Nam, Thailand, and Burma/Myanmar. Today, Hmong people live all over the world and call places like France, Australia, Canada, China, Thailand, Burma/Myanmar, Viet Nam, the U.S. home. My parents came from Laos.
> In the 70s, Hmong people in Laos (like my family) were thrust into the Viet Nam war, known as the “Secret War”. Hmong people in Laos were geographically situated in a strategic location and called upon the American CIA to help contain Communism by guarding the Ho Chi Minh trail, a network of trails that ran from North Vietnam to South Vietnam through the countries of Laos and Cambodia.
> Because of this involvement and siding with the Americans and against the governments of Laos and Viet Nam, Hmong people were persecuted. As a result, many Hmong fled to Thailand to seek refuge. My parents stayed in refugee camps in Thailand for a few years before being able to seek political asylum in the U.S. in the late 1970s.
> It is my pleasure to be able to volunteer my time to this cause.
> Thank you for all of your help.

**Comment by experimatt** [comment]
This is done!
