### ISSUE TITLE
Minimize title area clutter

### ISSUE THREAD

**Issue by experimatt** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#189]
This is part 1 of @estherrose046's suggestions from the other day. (Part 2 of her suggestions are documented in https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/issues/190):

- [ ] 1. We update the header of the legend to say "Twin Cities Mutual Aid Map" instead of "Twin Cities Aid Map"
- [ ] 2. We remove some of the padding/space between the legend header and the top item in the legend.
- [ ] 3. We remove the "status unknown" filter option, since we have basically eliminated that site category from the map. This and #2 clears up some space to add...

More detail in the [TCMAP Slack thread](https://tcmap.slack.com/archives/C014VT6ETUJ/p1592518802215700).

**Comment by experimatt** [comment]
Mockup for reference

![20200618_171643](https://user-images.githubusercontent.com/2946681/85233211-3c05cc00-b3ca-11ea-974f-72539a46881e.jpg)

**Comment by jdalt** [comment]
#192
