### ISSUE TITLE
Allow reporters to submit map updates through a text line (twilio)

### ISSUE THREAD

**Issue by jdalt** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#19]
<a href="https://github.com/mc-funk"><img src="https://avatars2.githubusercontent.com/u/10001418?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mc-funk](https://github.com/mc-funk)**
_Tuesday Jun 02, 2020 at 13:38 GMT_
_Originally opened as https://github.com/jdalt/twin-cities-aid-distribution-locations/issues/25_

----

Does anyone have time this morning (Tuesday) to get Twilio set up so that we can distribute a phone number for “penguins”, aka runners in the field getting site info,  to text, and it would go into our google workbook so that volunteers could review and then update the data? 

See: https://www.twilio.com/blog/2018/05/receive-sms-messages-google-sheets-apps-script.html

This would mean people in the field could get us an update without having to find Facebook or a form link.

Since Twilio has been outspoken I suspect they might also be open to giving us some help e.g. discounts. 

If someone can work on this this morning, I can get you the access you need to the spreadsheet, but you'll want to be in the OTC slack. 

No implementation direction as of yet, we'll need ideas on how to make this work well in terms of ease of use for both runners and data entry folks.

**Comment by jdalt** [comment]
<a href="https://github.com/experimatt"><img src="https://avatars0.githubusercontent.com/u/2946681?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [experimatt](https://github.com/experimatt)**
_Tuesday Jun 02, 2020 at 18:05 GMT_

----

I'm in touch with Kevin Whinnery from Twilio and can coordinate getting help here

**Comment by jdalt** [comment]
<a href="https://github.com/experimatt"><img src="https://avatars0.githubusercontent.com/u/2946681?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [experimatt](https://github.com/experimatt)**
_Tuesday Jun 02, 2020 at 19:51 GMT_

----

I emailed Kevin about this a little bit ago and CCed Michelle

**Comment by experimatt** [comment]
@maxine is working on this and in touch with folks at Twilio about it 🙌

**Comment by kmarekspartz** [comment]
Since there's now the email, we could pass along the texts to the email? Calls could be forwarded using Twimlets?

**Comment by maxine** [comment]
Update: Twilio is now set up so that the people maintaining the locations spreadsheet also have access to information from texts. @mc-funk is checking in with the organizing team for how to distribute the phone number to on-the-ground runners. @kmarekspartz not sure if calling was a feature that was requested, so may be worth waiting to add anything else until we see how the texts go.

**Comment by jdalt** [comment]
@mc-funk Can this be closed?

**Comment by experimatt** [comment]
+1 @maxine is this done? can we close this?

**Comment by maxine** [comment]
@experimatt @jdalt yes! closing now

**Comment by andyinabox** [comment]
@maxine Amazing! :100: :tada:
