### ISSUE TITLE
Change "seeking volunteers/seeking money" 

### ISSUE THREAD

**Issue by estherrose046** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#198]
We received feedback that our site's language was confusing to users - specifically that users were going to a site expecting to 'get' money rather than understanding it was a site that 'accepts' money. We believe the issue might be due to the word 'seeking' being an unclear/uncommon term. 
- "Seeking volunteers" should be changed to "Volunteer here" 
- "Seeking Money" should be changed "Donate Money Here"

**Comment by jdalt** [comment]
From @comeoneileen on [Slack](https://tcmap.slack.com/archives/C014VT6ETUJ/p1592970333240500?thread_ts=1592966477.237700&cid=C014VT6ETUJ):
> am also wondering if "sort by needs money" needs to change too...

**Comment by omawhite** [comment]
Going to go ahead and tackle this.
