### ISSUE TITLE
Unit test extractUrl function

### ISSUE THREAD

**Issue by emyl3** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#199]
There have been some bugs introduced with PR #168. Ideally, we can introduce a unit testing framework so we can test the `extractUrl` fn to ensure it is capturing all different variations of URLs that we may see in the Google Sheet.

**Comment by estherrose046** [comment]
This issue should be resolved with https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/pull/210
