### ISSUE TITLE
Improve symbolization for distribution locations

### ISSUE THREAD

**Issue by samanpwbb** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#2]
Right now the distribution location map uses mapbox's html markers: https://docs.mapbox.com/mapbox-gl-js/api/#marker

There are two usability issues:
- The markers aren't differentiated enough. We can use icons to represent different categories.
- There aren't text labels on the map, so markers are hard to scan, require interacting with them.

If we switched to a symbol layer (https://docs.mapbox.com/mapbox-gl-js/example/geojson-markers/), we'd be able to easily add labels, use custom images, and filter. This is something I can pick up this evening after we've moved to the new repo.

**Comment by kmarekspartz** [comment]
Perhaps emoji? 📥, 📤, ⛔️, 🔮 ? Not sure on the iconography here.

**Comment by samanpwbb** [comment]
Here's a sketch, is this worth continuing to pursue?
- Cluster dense areas
- Colored dot icon
- Text

![2020-06-03 21-13-50 2020-06-03 21_14_31](https://user-images.githubusercontent.com/108094/83714416-86700600-a5df-11ea-9201-6524c311cb13.gif)

**Comment by kmarekspartz** [comment]
I like the colored dot, not sure on the clustering. Asking a GIS expert... perhaps a semitransparent dot to account for overlapping points?

**Comment by kmarekspartz** [comment]
There's a PR #50 with proposed alternate color codes, too.
