### ISSUE TITLE
Map should include documentation about how to contribute to it

### ISSUE THREAD

**Issue by jdalt** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#20]
<a href="https://github.com/andyinabox"><img src="https://avatars1.githubusercontent.com/u/151084?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [andyinabox](https://github.com/andyinabox)**
_Tuesday Jun 02, 2020 at 13:51 GMT_
_Originally opened as https://github.com/jdalt/twin-cities-aid-distribution-locations/issues/26_

----

Related to #25 

The map needs to tell people how to update it. There’s that little Data Source thing on the legend now but that’s not terribly helpful since it just directs folks to read only google sheet. Things are changing on the ground so there’s not a ton of clarity here but we need  work with the folks bridging the development and pavement level volunteer efforts to communicate the process.

**Comment by jdalt** [comment]
<a href="https://github.com/mc-funk"><img src="https://avatars2.githubusercontent.com/u/10001418?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mc-funk](https://github.com/mc-funk)**
_Tuesday Jun 02, 2020 at 14:00 GMT_

----

I am hoping by midday today we will have (1) a google form and (2) a number to text.  We have someone working on the former and calls out for someone to work on the latter.

**Comment by experimatt** [comment]
This is partly covered by adding an "About this project" link which points to the readme, along with updates I just made to the readme.

**Comment by kmarekspartz** [comment]
Partially done in #43 and #47

**Comment by experimatt** [comment]
@mc-funk do you think we can close this, or at least move it to a lower priority? With email us and links to the repo on the site now I think this can be de-prioritized or closed.

**Comment by mc-funk** [comment]
Agree @experimatt let's close this.

**Comment by experimatt** [comment]
Thank you!
