### ISSUE TITLE
Contributing guidelines

### ISSUE THREAD

**Issue by jdalt** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#21]
<a href="https://github.com/andyinabox"><img src="https://avatars1.githubusercontent.com/u/151084?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [andyinabox](https://github.com/andyinabox)**
_Tuesday Jun 02, 2020 at 13:58 GMT_
_Originally opened as https://github.com/jdalt/twin-cities-aid-distribution-locations/issues/27_

----

From @jdalt on slack

> We could maybe use a pull request template and some thought as to how we’ll keep this code from getting too hairy. Things are working but eventually they won’t. Preparation always welcome.

**Comment by kmarekspartz** [comment]
Include QA guidelines.

**Comment by kmarekspartz** [comment]
Done in #56 ?

**Comment by jdalt** [comment]
The README and PR template sufficiently address this issue. We can certainly improve these, but that can be addressed specifically in each document now.
