### ISSUE TITLE
Replacing the back end sheet with a copy

### ISSUE THREAD

**Issue by comeoneileen** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#213]
The current owner of the Google Sheets document that is our backend...is someone who hasn't been part of this project for more than a month and hasn't answered emails. I'd like to do a "make a copy" on it so that one of our registered email addresses can become the owner, to remove the possibility that she cleans up her Drive and deletes the whole thing.

Here are things I know will need to change to make that happen:

- The public version of the data will need to draw from the new private sheet
- Everyone who has edit access will need to be given access to the new sheet/lose access to the old one so they don't update in the wrong place
- Pinned links/Slackbot auto-responses that spit out the link will need to be updated

@maxine and/or @mc-funk, what will need to be done in Twilio to make sure texts go to the new sheet?

Everyone else, what else am I missing?

**Comment by mc-funk** [comment]
We also have the timestamp and latlong scripts working in there -- I'm not sure if spreadsheet copies carry over the associated google scripts or not. That would be something to check, which would impact the Twilio scripting as well.

**Comment by maxine** [comment]
I don't think Google Scripts copy when you copy a spreadsheet, so once we move spreadsheets, feel free to ping me on Slack or email and I will set up the script in the new spreadsheet! Nothing will change on Twilio's side.

**Comment by comeoneileen** [comment]
Okay! Thank you both so much. That's a thing I'm going to try to tackle this weekend, then.

**Comment by comeoneileen** [comment]
Welp, this took forever, but @estherrose046 and I got it done. @maxine, texting with the new sheet is still buggy, but we're going to transition to using Google Voice instead so that we can also make phone calls, and I'll set up an autoresponder on Twilio to let folks know about the new number.
