### ISSUE TITLE
Add county level info (and neighborhood) to map through mapbox

### ISSUE THREAD

**Issue by estherrose046** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#219]
* display county level boundaries, neighborhood level boundaries
* automatically populate county information, neighborhood information 

Exploration of if we can / how we can implement this in mapbox. 
https://www.mapbox.com/boundaries/

**Comment by jdalt** [comment]
@samanpwbb Could you give us any guidance to doing the simple thing: displaying county level boundaries. Right now I imagine copying the theme from you account to mine and then doing some sort of style magic on the map to get county lines to appear.

Also if there's any guidance you might be able to offer for translating a latitude, longitude coord into all of the relevant containing boundaries...that would be cool too.

**Comment by samanpwbb** [comment]
@jdalt @estherrose046 I just spent 10 mins adding county info to the basemap tcma uses: https://api.mapbox.com/styles/v1/saman/ckawvg6bk011x1ipepu7nqlbh/draft.html?fresh=true&title=view&access_token=pk.eyJ1Ijoic2FtYW4iLCJhIjoiS1ptdnd0VSJ9.19qza-F_vXkgpnh80oZJww#8.83/44.9898/-93.2296

What do you think of this? I can publish these changes if it looks good!

Also: After publishing, would you prefer if the style got transferred over to your account? If yes I can help make that happen.

**Comment by jdalt** [comment]
@samanpwbb This looks great. Let's publish it!

Is it easy to copy this to another account? I'd love to at least have a copy to play with in my own account. Are there any down time concerns on a transfer?

**Comment by samanpwbb** [comment]
Just published. Here's a link to the style that you can copy: https://api.mapbox.com/styles/v1/saman/ckawvg6bk011x1ipepu7nqlbh.html?fresh=true&title=copy&access_token=pk.eyJ1Ijoic2FtYW4iLCJhIjoiS1ptdnd0VSJ9.19qza-F_vXkgpnh80oZJww

After you copy it, you'll need to swap the id here to use your copy: https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/blob/0ce32b0c112fab874e9373949c8661644d4f4a8c/src/index.js#L112

**Comment by amaxama** [comment]
Closing as we now have county lines through the style above, and neighborhoods also show up most of the time based on zoom level. Will still be accessible in closed issues!
