### ISSUE TITLE
Add code of conduct

### ISSUE THREAD

**Issue by jdalt** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#22]
<a href="https://github.com/samanpwbb"><img src="https://avatars0.githubusercontent.com/u/108094?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [samanpwbb](https://github.com/samanpwbb)**
_Tuesday Jun 02, 2020 at 17:22 GMT_
_Originally opened as https://github.com/jdalt/twin-cities-aid-distribution-locations/issues/31_

----

https://github.com/codeforamerica/codeofconduct is a good starting point

**Comment by jdalt** [comment]
We'll also need an official open source license. We'll need these to apply for Open Source status at Netlify: https://opensource-form.netlify.com/

**Comment by kmarekspartz** [comment]
It looks like GitHub has an easy way to add these: https://help.github.com/en/github/building-a-strong-community/adding-a-code-of-conduct-to-your-project
