### ISSUE TITLE
Add Mandarin Translations

### ISSUE THREAD

**Issue by amaxama** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#246]
Add translations from Mandarin column in [spreadsheet ](https://docs.google.com/spreadsheets/d/1XH6Nd4cnP6Ul5oU7vRzJYoB80_V56FzWwa0Vfc2Tabk/edit#gid=0)

**Comment by sj00coder** [comment]
I want to work on it.

**Comment by amaxama** [comment]
Oh shoot! I'm so sorry, I just saw your comment here now! I started the
work for this but there are some pending comments in the google sheet that
will require some updates to what's been started!
