### ISSUE TITLE
Update hamburger styles

### ISSUE THREAD

**Issue by jdalt** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#25]
<a href="https://github.com/jczaplew"><img src="https://avatars0.githubusercontent.com/u/1739551?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jczaplew](https://github.com/jczaplew)**
_Tuesday Jun 02, 2020 at 22:40 GMT_
_Originally opened as https://github.com/jdalt/twin-cities-aid-distribution-locations/pull/38_

----

This PR updates the styles of the hamburger to more closely match those of the geocoder and increase the target size of the button. I also removed the difficult-to-see citation from NounProject and replaced it with a credit in the `README`.

`master`:

<img width="374" alt="image" src="https://user-images.githubusercontent.com/1739551/83576631-c8258180-a4f7-11ea-8937-ea3bc7445ef5.png">

`hamburger-styles`:

<img width="376" alt="image" src="https://user-images.githubusercontent.com/1739551/83576558-a4fad200-a4f7-11ea-80e7-550893b7550f.png">

----

_**[jczaplew](https://github.com/jczaplew)** included the following code: https://github.com/jdalt/twin-cities-aid-distribution-locations/pull/38/commits_

**Comment by samanpwbb** [comment]
Closed by https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/pull/1
