### ISSUE TITLE
Update legend styles

### ISSUE THREAD

**Issue by jdalt** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#26]
<a href="https://github.com/jczaplew"><img src="https://avatars0.githubusercontent.com/u/1739551?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jczaplew](https://github.com/jczaplew)**
_Tuesday Jun 02, 2020 at 23:02 GMT_
_Originally opened as https://github.com/jdalt/twin-cities-aid-distribution-locations/pull/39_

----

This PR updates the legend styles to provide more room between elements on both desktop and mobile as well as eliminates a conflict between the legend and the Mapbox attribution elements on mobile.

`master`:

Mobile:

<img width="375" alt="image" src="https://user-images.githubusercontent.com/1739551/83577960-2d2ea680-a4fb-11ea-9f33-1b1b67d7ef31.png">

Desktop:

<img width="1196" alt="image" src="https://user-images.githubusercontent.com/1739551/83577937-2142e480-a4fb-11ea-8b73-e3acf2baf786.png">

`legend-styles` 

Mobile:

<img width="374" alt="image" src="https://user-images.githubusercontent.com/1739551/83577863-f48ecd00-a4fa-11ea-9ecd-b93e1becd6f8.png">

Desktop:
<img width="1201" alt="image" src="https://user-images.githubusercontent.com/1739551/83577905-11c39b80-a4fb-11ea-9dcb-32656411cd72.png">

----

_**[jczaplew](https://github.com/jczaplew)** included the following code: https://github.com/jdalt/twin-cities-aid-distribution-locations/pull/39/commits_

**Comment by jdalt** [comment]
<a href="https://github.com/samanpwbb"><img src="https://avatars0.githubusercontent.com/u/108094?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [samanpwbb](https://github.com/samanpwbb)**
_Wednesday Jun 03, 2020 at 02:54 GMT_

----

Hey @jczaplew – really appreciate you pitching in. Sorry for the disorganization but this project has moved to https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations.

**Comment by samanpwbb** [comment]
Closed by #1

**Comment by jczaplew** [comment]
Understood. Best of luck!
