### ISSUE TITLE
Add French Translations

### ISSUE THREAD

**Issue by amaxama** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#264]
French translations are ready to be added to the map - view translations here: https://docs.google.com/spreadsheets/d/1XH6Nd4cnP6Ul5oU7vRzJYoB80_V56FzWwa0Vfc2Tabk/edit#gid=0

**Comment by Dthurow** [comment]
I can take on this ticket, looks like no one else has claimed it so far?

**Comment by Dthurow** [comment]
Reading through the Language_Translation.md documentation, looks like it's out of date, since we no longer want to add flag icons ( #208 ), so I can update that document as well.

**Comment by Dthurow** [comment]
Also looks like some ids have been changed in the json files but not updated in the google doc https://docs.google.com/spreadsheets/d/1XH6Nd4cnP6Ul5oU7vRzJYoB80_V56FzWwa0Vfc2Tabk/edit#gid=0
That change was done in #211, I can update the google sheet ID fields to match that change, so the auto-generation of the JSON files specified in the Language Translation document still works.

**Comment by Dthurow** [comment]
Also had to update the id "filter_by_recieving" in the google sheets to the correct spelling "filter_by_receiving"

**Comment by Dthurow** [comment]
Added a pull request for my changes and requested a review from @amaxama since you opened this ticket, let me know if I should request a review from someone else instead!
