### ISSUE TITLE
Move secrets to Netlify environment variables

### ISSUE THREAD

**Issue by experimatt** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#27]
We're currently hard-coding our `mapboxgl.accessToken` and the `DATA_URL` variables in the code, and it would be much better to move them to Netlify environment variables.

**Comment by omawhite** [comment]
I could tackle this @experimatt if i got access to netlify.
I think moving these would be easy but we would then need a way for developer to get access to them for local development. I imagine just having everyone make their own .env file would work, but we would still need a way to let people on-boarding know what the secrets are.

**Comment by experimatt** [comment]
@omawhite sure, @jdalt, @andyinabox or I can add you to Netlify. What email is your netlify account associated with?

Also, I 100% agree with you that figuring out how to access ENV variables is the primary challenge here. I bet Jacob has some ideas.

**Comment by omawhite** [comment]
email: louiswhite3019@gmail.com

**Comment by experimatt** [comment]
@omawhite Shoot, I hit a snag. An extra seat on Netlify costs $15/mo.

If you want to go ahead and get it working locally with the ENV variables, I can add them in Netlify accordingly.

**Comment by experimatt** [comment]
Netlify docs, for reference: https://docs.netlify.com/configure-builds/environment-variables/#netlify-configuration-variables

**Comment by experimatt** [comment]
NOT PRESSING: @jdalt I just added ENV variables to Netlify per @omawhite's naming suggestions, but I'd like your perspective on which sensitive variable policy settings we should use. If the leave the default in place it'll require approval before preview builds get built. https://docs.netlify.com/configure-builds/environment-variables/#sensitive-variable-policy

**Comment by kmarekspartz** [comment]
I see the discussion on keeping the variables around, but also want to call out @eebbesen's suggestion from Slack of rotating the keys once they're secured.

**Comment by experimatt** [comment]
Blocked by https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/issues/15

**Comment by omawhite** [comment]
no longer blocked

**Comment by experimatt** [comment]
PR: https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/pull/93
