### ISSUE TITLE
Research and implement analytics solution

### ISSUE THREAD

**Issue by experimatt** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#29]
Research analytics options to gather analytics and re-use it in an ethical way.

Google Sheets might be a possible solution: https://mashe.hawksey.info/2014/07/google-sheets-as-a-database-insert-with-apps-script-using-postget-methods-with-ajax-example/

**Comment by experimatt** [comment]
Additional context from Eileen:
> Oh, and one other thing I THINK would be relatively easy: I know bigger analytics plans are in the works, but if we could prioritize getting an hourly view count logged, Dallas could stop trying to remember to write it down herself and stop melting down when she can't find the paper she's writing it on and that would be a vast quality of life improvement for everyone involved

She said Dallas is tracking hourly view counts "tbh for emotional validation"

**Comment by kmarekspartz** [comment]
Most relevant comment from #45: https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/issues/45#issuecomment-638547279

**Comment by jasonthibeault** [comment]
I use Google Analytics for each sub-site on my blog network (the-orbit.net), and it's free, and gives you the sorts of graphs they're looking for. I think this is going to be the easiest, fastest, cheapest option. Plus, we can delegate the domain's analytics to other people with Google accounts so we can just give Dallas and whoever else wants to see it, access directly. I can set this up on my own Google account since I happen to already have the ability to do multiple; all you'd have to add is a script in the footer to the <script> snippet. If this is acceptable to everyone, of course.

Privacy concerns would, obviously, include that we would then have access to where people came from to get to the site, as well as the possibility that Google might decide to use the data and share with law enforcement. But the same sort of thing might be true of Netlify if they were compelled to divulge.

Also, I'm personally VERY against us ever including a "locations near me" type button that requests your GPS -- anything that accidentally exposes someone to turning on their GPS unwittingly is dangerous.

**Comment by kmarekspartz** [comment]
Note that locations can be handled totally client side, though analytics might slurp it up if it is used.

–
Kyle Marek-Spartz

**Comment by experimatt** [comment]
I agree that Google Analytics would be the _easiest_ solution to pop in and get usage information. And I know there's a way to anonymize user IP addresses, which is _something_. If nothing else that would tell us what browser, screen size, device, and language people are using when visiting the site.

But I know Jacob and others have privacy concerns, which are 100% valid. I'm unfortunately not familiar with that many other web analytics offerings

**Comment by jasonthibeault** [comment]
I think the biggest privacy concerns are that: 

- Google scrapes EVERYTHING, all the time, and they're getting a little scary-big and a little scary-snoopish
- So does anyone else you set up analytics on
- That gives some outside org access to info we may not want them to have
- The same goes for the super simple French web-counter though

Not to put words in anyone's mouth, of course. But those concerns are going to exist everywhere. I think, ultimately, as long as we do what we can to anonymize what people can see, we've done our due diligence on our side, and if Google sells us out to law enforcement, then we never stood a chance at privacy anyway.

**Comment by jasonthibeault** [comment]
If we do go with this solution, I've created the tag and will implement the dashboard that people can view. Here's the code snippet -- it goes as the first line in <head> apparently.

`
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-9313001-2"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-9313001-2');
</script>
`

**Comment by experimatt** [comment]
@jasonthibeault if we end up using GA, I think IP anonymization would be a hard requirement. https://support.google.com/analytics/answer/2763052?hl=en

**Comment by benjifs** [comment]
I was just testing something out with Google Analytics and exporting reports to spreadsheets. I think one of the things we talked about on Tuesday was about transparency and having the users being able to get access to this data.

I just tried running automated analytics to a google sheet from my websites analytics and it works fairly well. There's a lot of options there in terms of what data we can show but we can schedule that to run every night and have that report be publicly accessible. Maybe I misunderstood this part but just putting that out there as an option.

**Comment by jasonthibeault** [comment]
Looks like with the gtag format you modify as follows: 

gtag('config', '<GA_MEASUREMENT_ID>', { 'anonymize_ip': true });

I'll update the above snippet to reflect this

**Comment by caseyhelbling** [comment]
Chatting more with @benjifs in slack about getting the base GA implementation out first and then iterating -- possibly adding event tracking to get more fine-grained use analytics. If we launch GA and look at the reports and it isn't meeting our needs we'll shut it down. Does anybody object to this approach? If not I recommend we get that PR whipped up.

**Comment by experimatt** [comment]
I think we need to get something out there, and the longer we wait the more we're going to be lacking hard data to help us continue to iterate and improve. We need to get something out there, and I think we should proceed with GA

**Comment by experimatt** [comment]
@jasonthibeault this was just merged in with https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/pull/87. Can you add all of us to the GA project, at your convenience?
