### ISSUE TITLE
Volunteer availability and talents list

### ISSUE THREAD

**Issue by jasonthibeault** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#3]
Need to put together a page on the wiki so we know who each other is, what our availability is, handles on the Slack, and particular skillsets. Please sound off here.

Jason Thibeault - @Jason Thibeault - available 10am - 10pm CT
Ops guy, Python, networking and DNS, data transformation, Google Scripts, spreadsheet gruntwork
Not local to Twin Cities right now :( , can't do any calling around etc

**Comment by omawhite** [comment]
Omar White - @omar - available after 5pm CT
Front end guy, javascript, react mostly, done some python in the past, some cloud and ops stuff too. Local to the twin cities.

**Comment by samanpwbb** [comment]
Saman Bemel-Benrud - @samanpwbb - available intermittently ~10am - 10pm CT
generalist programmer (front and backend) and product designer, with particular expertise in Mapbox and mapping.

**Comment by cwood821** [comment]
Christian Wood - @cwoo821 - available MWF after 5:30pm 
front and backend programming, devops stuff; have worked with Google Apps Script and Mapbox. Also happy to jump on any grunt/background tasks.

**Comment by experimatt** [comment]
Matt Decuir - @experimatt  - available intermittently throughout the day
Most experienced w/ Ruby/Rails, React, javascript, SQL, spreadsheets, product, and community-oriented projects like this. Based in St Paul

@jasonthibeault should we move this issue to the wiki now that it's setup?

**Comment by jdalt** [comment]
Jacob Dalton - @jdalt - available on Slack but working the day job during the 10-6 time frame.
Experienced Ruby on Rails, maps, React, Angular, Github, hackathons, and product development.

Contact me on Slack if you need administrative work or PRs merged.

**Comment by experimatt** [comment]
@jasonthibeault Nice work! Now that everything's in sync between the issue and wiki I'd say we should close the issue. That way we can try to use issues only for tasks. 

I'll close it for now, but feel free to reopen if you disagree (no offense intended or taken)
