### ISSUE TITLE
Improvements to "Needs Money Donations" 

### ISSUE THREAD

**Issue by estherrose046** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#31]
Currently this button works by regex parsing the text of the fields "notes," "accepting" and "urgentneed" and searching for money-related terms. 

https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/blob/master/script.js#L165-L166

```
        const moneySearchStr = `${item.gsx$accepting.$t}, ${item.gsx$urgentneed.$t}, ${item.gsx$notes.$t}`.toLowerCase()
        const seekingMoney = moneySearchStr.includes('money') || moneySearchStr.includes('cash') || moneySearchStr.includes('venmo') || moneySearchStr.includes('monetary')
```

We can improve this by adding a boolean value to the spreadsheet for "needs monetary donations" as well as a spreadsheet field with the link to donate. The boolean would toggle the visibility of the donation link and trigger the visibility of the "Needs Money Donations" label. Reasoning: some sites will have specific fundraising needs and once they are met for that day, we will want to remove the visibility of the donation link.

The volunteers update the spreadsheet throughout the day and have an evening review for each site to re-evaluate their needs.

**Comment by jdalt** [comment]
Making it easy to donate money is in high demand from sites since many have enough "stuff". Making this easy on mobile would have large benefits.

**Comment by caseyhelbling** [comment]
Picking this up - Who do I talk to about adding the column 'seekingMoney' (boolean), and 'seekingMoneyURL' ?

**Comment by kmarekspartz** [comment]
Relaying from Slack: This can be done after-hours, not while people are live updating the Google Sheet.
