### ISSUE TITLE
Use a Facebook Preview Image Like the Favicon

### ISSUE THREAD

**Issue by jdalt** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#33]
The current facebook image (and original favicon) https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/blob/master/images/aid.png 
![aid](https://user-images.githubusercontent.com/2358067/83597257-7ba86900-a52c-11ea-8ada-acea0a940151.png)
was something I bought from the noun project. Later some fine person named Alex built the amazing pixel art favicon we're using.

For your consideration: should the facebook image match the favicon? See the attached files:
![icon256](https://user-images.githubusercontent.com/2358067/83597160-31bf8300-a52c-11ea-8aac-406d3a3e6381.png)
![icon512](https://user-images.githubusercontent.com/2358067/83597161-31bf8300-a52c-11ea-8b49-70b9628bba3b.png)
![icon1024](https://user-images.githubusercontent.com/2358067/83597162-31bf8300-a52c-11ea-92c7-90e8633f6695.png)

**Comment by jdalt** [comment]
If we want to use the current image we should at least crop it and consider using a different color - it looks awful in facebook's dark mode.

**Comment by andyinabox** [comment]
I vote for the pixel art! Love it.

**Comment by nucleargriff** [comment]
I also like the pixel art. Can knock this one out right now if that is the consensus.
