### ISSUE TITLE
Add email link to support@twin-cities-mutual-aid.org

### ISSUE THREAD

**Issue by mc-funk** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#37]
How trivial would it be to set up a support@ email address? 
I would take the lead on monitoring. We could link it from the map as well.

**Comment by jdalt** [comment]
I have the domain at name cheap. I think we could do something like create a google group and forward emails to people how can handle things.

**Comment by jdalt** [comment]
Actually I can just get this puppy to forward real fast. This is what I can do at Namecheap:
<img width="1442" alt="Domain" src="https://user-images.githubusercontent.com/2358067/83656259-f00ef680-a584-11ea-9925-d3e3894e736f.png">

**Comment by mc-funk** [comment]
OK, we need to get an email that the support can forward to. This is going to take priority over the form effort etc.
