### ISSUE TITLE
Log views over time

### ISSUE THREAD

**Issue by mc-funk** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#45]
Org side would love to know the trend on views hour by hour. Does our view counter make this easy to do?

**Comment by kmarekspartz** [comment]
It does not appear so: https://www.websiteout.net/counter.php

Perhaps Netlify has some baked-in data analytics?

**Comment by experimatt** [comment]
@kmarekspartz I just saw that Netlify has an analytics offering that costs $9/mo, but I don't know if that will allow us to get the data out of Netlify to display on the site. https://docs.netlify.com/monitor-sites/analytics/

It also occurs to me that we might have Cloudflare setup, which also might give us access to high level view data

**Comment by experimatt** [comment]
Also, this issue may be a duplicate of https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/issues/29

**Comment by mc-funk** [comment]
Dallas' partner was able to get a rad little screenshot solution working for this specific need, I'll close this since anything related would fall under #29.

**Comment by experimatt** [comment]
@mc-funk amazing!
