### ISSUE TITLE
tcmap.org landing page

### ISSUE THREAD

**Issue by mc-funk** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#46]
I bought www.tcmap.org as that acronym is what the org side of things have settled on. 
currently it just redirects to www.twin-cities-mutual-aid.org. 

next we're going to to a basic landing page that includes our written PR statement and links to both of our map projects. 

this will eventually be the "about this project" link to supplant the repo link in #43

**Comment by jdalt** [comment]
So will this also cover the store open/closed map?

**Comment by mc-funk** [comment]
@jdalt not sure what you mean by "cover",  but yeah this will just be a landing page that contains a statement about the project and links to the two sites, the Store Open/Closed Map, and the Aid Sites map.

**Comment by kmarekspartz** [comment]
Minor note, you may want to distinguish between this and http://maptime.io/msp/ (as well as invite them to help!)

**Comment by experimatt** [comment]
@mc-funk we could easily throw up a github page site for tcmap.org. that might be the simplest starting point, and it could belong to this org.

**Comment by mc-funk** [comment]
This is evolving into a WordPress site for TCMAP so i'll close for now. @kmarekspartz maptime looks adorable.
