### ISSUE TITLE
A nice API for the Google sheet

### ISSUE THREAD

**Issue by Flet** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#48]
Hello! 👋 

This is a really great effort and I would love to contribute!

I noticed the sheet is being pulled in and parsed on the browser, which can be super annoying and cumbersome to deal with. So I stayed up (way too late) and built a nice API that sits in front of a google spreadsheet and exposes the rows through a REST endpoint.

https://github.com/flet/nice-api

I set up an instance of this API on Glitch, backed by the spreadsheet used on the site. 
It relies on [FeathersJS](https://docs.feathersjs.com/guides/) for most of the work. The API fetches the data from the google sheet and caches it in memory for 5 minutes.

Here are some Example URLs:
 - All rows (paginated): https://flet-nice-api.glitch.me/rows
 - All rows (page size 1000): https://flet-nice-api.glitch.me/rows?$limit=1000
 - Filtering and selecting specific fields: https://flet-nice-api.glitch.me/rows?neighborhood=Midway&$select[]=nameOfOrganization&$select[]=latitude&$select[]=longitude

Does this sound appealing to use? The API could be forked and modified to further optimize/massage the data to make it even more useful for this data set. This could offload some of the heavier lifting that the client is doing now (filtering and massaging stuff) and allows for even better ops the future (using a real database, more robust hosting, etc).

Thank you starting this effort!

**Comment by Flet** [comment]
This could be hosted on glitch to start and moved somewhere else if folks find a nice place for it to live.

**Comment by andyinabox** [comment]
Whoa this is cool! :100: 

One thing that occurs to me is that, since we're using Netlify, we might be able to deploy this as a serverless function within our repo: https://docs.netlify.com/functions/build-with-javascript/#format. Not sure what it would cost, but maybe we could get Netlify to comp.

It might be a little while before we consider moving to something like this since we're still in the thick of getting some basic usability stuff figured out. If you want to keep helping in the meantime, check out the high priority issues (or the rest) and see if any sound interesting:

https://github.com/orgs/Twin-Cities-Mutual-Aid/projects/1

**Comment by Flet** [comment]
Thanks for the feedback @andyinabox! 

I think the project link you shared is currently not public. :)

**Comment by experimatt** [comment]
@Flet the project page should be public now, sorry about that!

**Comment by Flet** [comment]
#### How would data model changes to the spreadsheet be handled? What would be a breaking change, and how could their impact be mediated or worked around?

The API just pulls the names of the columns in a sheet and turns them into camelCase properties. Its a scrappy approach that sidesteps the formalities of an actual database, so it does rely on those names not changing (same risk as today). The goal is to make sheets easier to consume by exposing them through a more standard REST API. We could totally bootstrap this into something sturdier as times goes on and resources are secured (maybe a DB, hosting, etc).

#### How do teach it? How do explain to new developers how this backend middle layer works?

The API runs on express and was built using [FeathersJS](https://feathersjs.com/). There is a lot of great documentation available at their site. The majority of the code in the project was generated by the feathers CLI (`feathers generate app`).

The only real custom logic is the [hook](https://docs.feathersjs.com/guides/basics/hooks.html#quick-example) that runs before each request that will [refresh the spreadsheet](https://github.com/Flet/nice-api/blob/master/src/hooks/refresh-sheet.js) if the data in memory is older than 5 minutes.

#### Can we keep it all in one repo and one deployment solution? Can Netlify be a one stop shop?
Yes! I was able to convert `nice-api` into a Netlify function and update the client side script to use it. 
Here is a copy of it deployed to Netlify with the function in use:
https://musing-shannon-4a3e99.netlify.app/
 -  API_KEY and SHEET_ID are all set as environment variables in Netlify that are picked up by the function
 - happy to add folks to the netlify site if they want to poke at it too.

Here is the branch with the updates:
https://github.com/Flet/twin-cities-aid-distribution-locations/tree/netlify-serverless
The function is under `/functions/api`

The script,js updates show all the funky `gsx$` stuff removed: 
https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/compare/master...Flet:netlify-serverless#diff-9a9569e9d73f33740eada95275da7f30

If this is picked up, I think the `seekingMoney` and location transformations could be moved into the API pretty quickly.

#### How do we continue to support a simple batteries included local development experience?

The only prerequisite is having node installed.
Right now to develop locally, it would be:
```bash
npm install
npm run dev # runs npx netlify dev, which handles the static content as well as the function
```

**Comment by experimatt** [comment]
Note: I'm not adding this to the GH Project because it's more of an open discussion & documentation issue than actual task.

**Comment by amaxama** [comment]
Closing this as we now have a backend api and are no longer using google sheets. Will still be accessible in closed issues!
