### ISSUE TITLE
Reduce the height of the title area on mobile

### ISSUE THREAD

**Issue by samanpwbb** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#57]
Here's what the app looks like on an iPhone SE:

<img width="328" alt="Screen Shot 2020-06-03 at 6 14 22 PM" src="https://user-images.githubusercontent.com/108094/83704500-16558600-a5c7-11ea-8ee2-fa0eacb1ba94.png">

As a consequence of a few recent changes, there's not enough room on the map to display tooltips. Some recommendations for consolidating the top section:

- Move to two columns instead of one for the legend (this may also require some minor copy tweaks).
- Move all secondary links behind a toggle.

**Comment by samanpwbb** [comment]
Here are some quick mock-ups:

![Screen Shot 2020-06-03 at 7 20 29 PM](https://user-images.githubusercontent.com/108094/83707660-57ea2f00-a5cf-11ea-83cf-2bab62792941.png)

![Screen Shot 2020-06-03 at 7 20 26 PM](https://user-images.githubusercontent.com/108094/83707668-5caee300-a5cf-11ea-91d3-0b5e64686710.png)

**Comment by samanpwbb** [comment]
I don't think we should add scroll since scrolling sites + maps = bad times wrt usability. Here's another option that is similar to scrolling though: Add a swipe event handler to the title area. If user swipes the top section of the site, collapse it:

![Screen Shot 2020-06-03 at 7 32 34 PM](https://user-images.githubusercontent.com/108094/83708366-fe82ff80-a5d0-11ea-8f52-d36dc66137af.png)

**Comment by kmarekspartz** [comment]
A 2016 iPhone SE, even worse:
![6A4E03EF-CBFC-4A46-B32C-AC998EEA5372](https://user-images.githubusercontent.com/969868/83708848-d56b6a80-a5e2-11ea-9c2a-ac816fc3f5b4.png)

**Comment by kmarekspartz** [comment]
I’m a hamburger skeptic but that might be the right thing here

**Comment by jdalt** [comment]
I like suggestion 2 for its simplicity: less busy, lots of space, and buttons are simple and discoverable. I think @mc-funk probably has sign off on this.

**Comment by andyinabox** [comment]
We'll also have to consider where to put the translation menu once #40 is ready to merge.
![Screenshot 2020-06-03 22:36:52](https://user-images.githubusercontent.com/151084/83712192-c8eb1000-a5ea-11ea-9a42-7ab624874e97.png)

**Comment by jdalt** [comment]
@andyinabox I've been thinking about that too. PRs are piling up right now.

**Comment by samanpwbb** [comment]
> We'll also have to consider where to put the translation menu once #40 is ready to merge.

Consider handling translation with an immediate popup the first time user visits the site that asks user for preferred language, and then saving the result to localstorage. We can then put the language toggle behind help/info.

**Comment by samanpwbb** [comment]
It sounds like there's some consensus around https://user-images.githubusercontent.com/108094/83707668-5caee300-a5cf-11ea-91d3-0b5e64686710.png – would be great for someone to pick up the implementation. I recommend using a target selector (https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Selectors/Using_the_:target_pseudo-class_in_selectors) and a url fragment (#info).

**Comment by experimatt** [comment]
@samanpwbb I'm working on this right now. If you have any code handy that you used to mock up the consensus version, please send it over!
