### ISSUE TITLE
Filter map markers based on sidebar filters

### ISSUE THREAD

**Issue by samanpwbb** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#6]
Separating this from https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/issues/2, because I think this is the higher priority issue. 

Right now the app allows users to filter locations in the sidebar, but the map does not filter these locations. We've heard feedback that this has been a point of confusion for some users.

There are a few ways to fix this, but here are the two I'd suggest:

1. Markers are currently html elements. We can use dom manipulation to hide them: when a filter is selected, apply a class to all markers that we want to hide, or apply a class to container around markers and then use CSS to hide markers not matching the active class.
2. Switch to a Mapbox symbol layer and use feature state or geoJSON feature filtering (see https://docs.mapbox.com/mapbox-gl-js/example/geojson-markers/ / https://docs.mapbox.com/mapbox-gl-js/api/#map#setfeaturestate.

**Comment by benjifs** [comment]
Working on this. The first approach seems to be the way to go about this until we can switch to geoJSON. Also good for reference: https://docs.mapbox.com/mapbox-gl-js/example/filter-markers/

**Comment by kmarekspartz** [comment]
An attempt in #34

**Comment by jdalt** [comment]
Completed in https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/pull/35
