### ISSUE TITLE
Published version of the source data not user friendly

### ISSUE THREAD

**Issue by estherrose046** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#62]
I have received some feedback today that the source data, when linked from the map, leads to a spreadsheet without a fixed header row and location side-bar. This seems to be interfering a lot with usability. 

As per this explanation, when google docs are published to the web they can't have fixed rows and columns: https://support.google.com/docs/thread/10058220?hl=en

Do we want to link to the read-only view of the spreadsheet instead of the published to web version?

Now: 
<img width="832" alt="Screenshot 2020-06-03 22 53 43" src="https://user-images.githubusercontent.com/21974228/83713241-3304b480-a5ed-11ea-90da-238cac49ab0e.png">

Suggested change:
<img width="814" alt="Screenshot 2020-06-03 22 54 27" src="https://user-images.githubusercontent.com/21974228/83713336-6b0bf780-a5ed-11ea-9f26-7ec15a6d891f.png">

**Comment by jdalt** [comment]
@experimatt I believe that's the correct link (should match what the webapp is pulling from).

Anyone know if there's a way to prevent the appearance of being able to edit?

**Comment by experimatt** [comment]
@jdalt 👍, no idea on being able to edit.

Assuming we want to make this change, this would be a great first contribution for a new person

**Comment by experimatt** [comment]
This is done
