### ISSUE TITLE
COVID precautions?

### ISSUE THREAD

**Issue by kmarekspartz** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#63]
Another aspect of security (#36) is health protocols, brought up on Twitter by Tana Hargest: https://mobile.twitter.com/TanaHargest/status/1268174068349636610

We may want to track another column for COVID precautions.

**Comment by jdalt** [comment]
I think this is a good idea. I'd be interested in what organizers and site operators think about this.

**Comment by andyinabox** [comment]
Maybe we could include info about testing?

**Comment by mc-funk** [comment]
I don't know if we're actively seeking this information, but it does make its way into notes frequently. 
This is the kind of consideration to keep in mind as we move out of crisis mode, and if we're going to try to move towards having sites enter their own data it'll be relevant for people. 

Not sure how testing plays in, I do know testing sites have been cited as a possible use of the map though.

**Comment by andyinabox** [comment]
I'm still thinking about how this would work in practice, and don't want this issue to flounder. It feels like more of an on-the-ground effort to be addressed by the broader TCMAP group, and the map can only reflect that effort. But here are a few ideas of things we might track

 * Has clearly posted COVID guidelines at site
 * Has PPE available for volunteers to use
 * Has sanitization protocols in place
 * Is enforcing social distancing guidelines

But as I think about this, I worry about penguins becoming "inspectors," which seems like a weird dynamic. Also I'm writing this having only spent time at one donation site and having a minimal sense of what things are like on the ground in general.

**Comment by mc-funk** [comment]
Those are all very good concerns @andyinabox ... one similar issue that has come up is that of acceessibility. It's a lot to put on penguins in terms of information gathering and communication -- but we would also love for e.g. wheelchair users to be able to know which sites are accessible to them.

I think at this point we know we are handling testing sites in another ticket, and it seems like (forgive me for not looking now) we are moving towards a "services" model for listing out things available at the site. Maybe "services" could include accessibility features, which to my mind includes COVID precautions.

**Comment by mc-funk** [comment]
This should be at least partially addressed by #161 and #160
