### ISSUE TITLE
Combine filter into legend

### ISSUE THREAD

**Issue by kmarekspartz** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#7]
This site no longer works because Firebase shutdown, but it may have what we need for the logic: http://mary.marek-spartz.org/suggestionbox.html

<img width="217" alt="image" src="https://user-images.githubusercontent.com/969868/83587309-68899f00-a514-11ea-8ad3-4a8fd6dd5d08.png">

**Comment by samanpwbb** [comment]
Ya, right now we have these two different elements and I think they could be one element:

![Screen Shot 2020-06-02 at 7 02 13 PM](https://user-images.githubusercontent.com/108094/83587375-cd88c900-a503-11ea-8c75-649d3aa75d9a.png)

**Comment by kmarekspartz** [comment]
I'm not seeing either of those on https://twin-cities-mutual-aid.org, seeing this instead: 
<img width="166" alt="image" src="https://user-images.githubusercontent.com/969868/83589872-1e0b2100-a51a-11ea-860c-48e2eb603ee7.png">

**Comment by benjifs** [comment]
Maybe related but depending on the resolution, I'm getting a weird bug where the top area with the legends increases in size if you click some of the checkboxes. Quick fix seems to be to remove the `height: 100%;` from the `.title`.

I can work on this issue but just curious, what is the best way to visualize this? Here's the two quick suggestions:

![Legends with background-color](https://user-images.githubusercontent.com/4167938/83592335-ace36200-a549-11ea-9b53-2600fd6fff48.png)

![Legends without background-color](https://user-images.githubusercontent.com/4167938/83592339-afde5280-a549-11ea-9c39-3eaf8caeb42a.png)

For the second option the last item is barely visible so maybe the first unless there are other suggestions

**Comment by samanpwbb** [comment]
Top option should work well especially if filters also apply to the map points

**Comment by benjifs** [comment]
Awesome. I'm submitting a PR for this and #6 in a little bit

**Comment by kmarekspartz** [comment]
@benjifs pushing one now!

**Comment by kmarekspartz** [comment]
An attempt in #34

**Comment by jdalt** [comment]
Completed in https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/pull/35
