### ISSUE TITLE
Research using Notion as a Complimentary or Primary Backend Data Source

### ISSUE THREAD

**Issue by jdalt** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#72]
There's an additional effort get people tools to communicate and organize aid:
https://www.facebook.com/heyalexjames/posts/3123367681054588
https://www.notion.so/GeorgeFloyd-BLM-Resource-Guide-b5d1dc40412a4f938acea7fd07484509

By all accounts Notion is a pretty solid tool for this. It may allow individuals to enter, update, and own the data for their sites as well as facilitating a bunch of other interactions we don't support.

It's not clear right now whether the Notion data should be a parallel effort or primary source of truth. We need to investigate what it would take to use this data as a Complimentary and as Primary data source.

**However this is not merely a technical challenge.** More importantly, this is an organizational challenge. We need a complete plan with training ready, if this were to become the primary backend data source.

So let's put on our thinking caps and get to researching.

Things that I think we need to learn about:

1. What are the data recording capabilities of Notion? We’ve built our spreadsheet to work with a map - notably geocoding addresses to lat, lon -- so that we can map sites. If we can’t get mappable data out of Notion then we go forward in parallel and discuss how to upgrade that to symbiotic.
2. Understand the Penguin/Lizard effort in much more depth. What hurts right now and how can we make it better. Can Notion help us here?
3. We need to explore what API access to Notion looks like.
4. We need to understand the data entry capabilities of Notion and how the Penguin/Lizard model could work with that.

The big questions is **can we be a single data source** and **can we be a single organization**? Being separate and complimentary is a perfectly reasonable conclusion. Our decision needs to be guided by our technical and, foremost, organizational needs

**Comment by samanpwbb** [comment]
Another option is to have a conflation layer. The frontend is a unified app that pulls from two different sources with two different schemas, and normalizes /dedupes them for display.

**Comment by jdalt** [comment]
@samanpwbb That would dovetail nicely with the efforts and work in this issue: https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/issues/48

**Comment by experimatt** [comment]
A friend who's both a software engineer and notion enthusiast said that while their API isn't public yet, a handful of people have reverse engineered it.

He just pointed me to the [react notion](https://github.com/splitbee/react-notion) repo, which uses [notion-api-worker](https://github.com/splitbee/notion-api-worker) under the hood to interact directly with notion.

**Comment by unsay** [comment]
Hi @jdalt, been a while. Thanks everyone for this project. It was invaluable for me as a donator.

I’ll think about this too: I’m the Notion wonk @experimatt alluded to.

**Comment by experimatt** [comment]
I emailed and [tweeted](https://twitter.com/experimatt/status/1268652996487008256) at notion yesterday. They just responded to my tweet saying they're working through the queue right now and will hopefully respond soon. I'll report back when I hear from them.

**Comment by experimatt** [comment]
Email response from Andy at Notion:

> Hi, Matt! 
> 
> Thanks for reaching out about this and for the work that you're doing on BLM. While this is a worthwhile initiative and we're excited to support it, unfortunately we can't grant access to our API sweat_smile Sorry about that! 
> 
> I did however upgrade your workspace to a free Team Plan (no limitation for members and no expiration date)!
> 
> Here's our Notion for Teams guide and Invite teammates guide to help you get settled into your workspace, if you haven't already.
> 
> Here are some other resources that might be helpful:
> 
> question Notion Guides & FAQs page
> movie_camera Videos from our YouTube channel
> woman🏻‍computerNotion Office Hours - LIVE sessions with an expert every Friday
>  Notion on Insta - Tips, tricks & sneak peeks from HQ
> sparkles Template Gallery - lots of interesting use cases for Notion on this page!
> 
> 
> Here's a BLM guide someone else from our community made - a living resource supporting Black communities & allies in safely strategizing, organizing, and mobilizing across the US. Please share with your organization as well!
> 
> A workaround for not having the API is to embed Google Sheets into Notion instead.
> 
>  "/embed" will create an iframe with a two-way sync. This will allow you to make edits in your Google file from within your Notion page and have those edits show up in the actual Google file. You'll need to copy and paste the URL of the Google file into the Embed block. The Google file must also be connected to the same email address as your Notion account.
> 
> "/google" will create an image snapshot of your file from Google Drive. You won't be able to make edits in your Google file from within your Notion page. It acts as a bookmark directly to your Google file. Using this Google Drive block will allow you to connect multiple Google accounts directly to your Notion account, then search for and select your file from a Google Drive menu.
> 
> Does that help? You can read more about Google embeds here. Let me know if you have any further questions!

**Comment by jdalt** [comment]
@unsay Great to see you again! Leaders from the two biggest civic tech projects I had previously worked on are here in current biggest project.

Do you have any thoughts on how we could merge these two efforts together? The lack of official api access is quite limiting. I'm not opposed to a workaround hack based on https://github.com/splitbee/notion-api-worker + an api shim.

What do you think is possible?
