### ISSUE TITLE
Indicator for locations that are "opening soon"

### ISSUE THREAD

**Issue by experimatt** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#74]
Suggested by @estherrose046, related to PR https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/pull/71 that was just merged:

> I think there should be a follow-up discussion about having a way of indicating sites that are "opening soon"

**Comment by andyinabox** [comment]
I love that we're basically building Yelp for taking care of people...

**Comment by amaxama** [comment]
Working on this

**Comment by sbeins55** [comment]
Currently working through ideas on how to best represent `Opening Soon` concept.

We've played with the idea of additional chips or modifications directly to the cards like the below. Our worries with this approach is that users would not see locations that are opening soon unless they specifically choose to filter by closed locations.
![image](https://user-images.githubusercontent.com/26053689/83906608-8419c300-a729-11ea-8a5c-8d0827d7ec19.png)


We have also played with the idea of additional filter options like the below. Our worries here is the filter options are starting to grow a little too much.
![image](https://user-images.githubusercontent.com/26053689/83907269-c68fcf80-a72a-11ea-88b1-aaf4c40a1dde.png)

Are there any preferences to how this is implemented?

**Comment by amaxama** [comment]
@experimatt Opening this discussion above - not sure if there's a better way to get feedback

**Comment by experimatt** [comment]
It's really important that we minimize adding height to this section because on mobile it eats up way too much screen real estate.

there was some chatter last night about how we should display information in situations when everything is currently closed. @caseyhelbling I believe mocked up showing the number of locations in each category (i.e. "currently closed (47)"), but it doesn't look like we implemented anything like that.

I'd defer to @estherrose046 for her take here, but my gut says we could do some wizardry to lump the "opening soon" locations in under the current "open" categories, and then flag "Opening soon" next to the title of the location. That way we wouldn't add more filter options and minimize the height of the title area . I hope that makes sense

**Comment by estherrose046** [comment]
I am going to field this to the #dragonrider channel / organizational side and see what they think, thank you so much for the awesome ideas!

**Comment by amaxama** [comment]
@experimatt That's kind of what I was thinking with lumping the opening soon under the "open" categories, but will wait to hear back from @estherrose046

**Comment by sbeins55** [comment]
> It's really important that we minimize adding height to this section because on mobile it eats up way too much screen real estate.
This section refers to the filters?

> there was some chatter last night about how we should display information in situations when everything is currently closed. @caseyhelbling I believe mocked up showing the number of locations in each category (i.e. "currently closed (47)"), but it doesn't look like we implemented anything like that.
I can see this helping address our worries with just the labels!

> I'd defer to @estherrose046 for her take here, but my gut says we could do some wizardry to lump the "opening soon" locations in under the current "open" categories, and then flag "Opening soon" next to the title of the location. That way we wouldn't add more filter options and minimize the height of the title area . I hope that makes sense
This does, thanks! 

Thanks @estherrose046 for helping out!

**Comment by estherrose046** [comment]
I like the idea of clumping "opening soon" with "open." 

At one point we were thinking of adding "flags" to pins - this might be super helpful in this situation. I think @samanpwbb was working on pins and has a pull request open: https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/pull/64

**Comment by experimatt** [comment]
> > It's really important that we minimize adding height to this section because on mobile it eats up way too much screen real estate.
> 
> This section refers to the filters?

@sbeins55 yes, the blue area with the filters is what some devs refer to as the title area. Screenshots of how much space it takes up on an iPhone 5/SE sized screen included below for reference. We _really_ don't want to make the blue section any taller if we can avoid it.

![Screen Shot 2020-06-05 at 1 41 20 PM](https://user-images.githubusercontent.com/2946681/83911790-80d70500-a732-11ea-9ad8-02502b060615.png)

![Screen Shot 2020-06-05 at 1 41 31 PM](https://user-images.githubusercontent.com/2946681/83911774-761c7000-a732-11ea-84d6-f27a36e6bb99.png)
