### ISSUE TITLE
Make last-updated much more prominent on pin popups

### ISSUE THREAD

**Issue by jasonthibeault** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#75]
User feedback was given that people have driven miles to stores that turn out to not have up-to-date needs lists right now and didn't need / didn't have what was listed. We should move "last updated" to the top of the pin data so people aren't driving for no good reason. Also, possibly, style it so it's more visible -- somehow. Anything to draw attention to when the data was actually vetted.

**Comment by arich** [comment]
I was playing around with using moment.js to do a fancy "8 mins ago", "4 days ago" kind of ambiguation, but I'm not that actually adds any value here. Thoughts?

**Comment by arich** [comment]
Examples.
![Screen Shot 2020-06-04 at 10 43 35 PM](https://user-images.githubusercontent.com/852709/83834811-dc62ad80-a6b4-11ea-9094-cd47435f9bd9.png)
![Screen Shot 2020-06-04 at 10 43 19 PM](https://user-images.githubusercontent.com/852709/83834813-dd93da80-a6b4-11ea-8b75-830b196e12ea.png)

**Comment by caseyhelbling** [comment]
I think using moment.js is a nice addition provided the words can be i18n. We might want to visually extract that row as we do the neighborhood and address to really draw attention to it. Thoughts?

**Comment by arich** [comment]
Definitely. I'm not too much of a UXer but I'll give it a shot. Or, I'll put up the PR I have ready to go and refine it from there.
