### ISSUE TITLE
Reported issues with map loading

### ISSUE THREAD

**Issue by mc-funk** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#86]
We haven't been able to consistnely reproduce, but in the last hour 9-10amCT Friday, we've received scattered reports of issues with page loading. Filing this issue quickly in expectation that more detail can be filled in in comments.

**Comment by formicadinette** [comment]
2 users reported to me at 10a CT that the map was blank and refreshed multiple times. One finally had it correct and the other had it start showing orange and blue but then not fully function until a few minutes later. It was working for me during this time but I had it loaded and did not refresh. I did see some strangeness earlier where it showed all the checkboxes checked but also didn't appear to show everything on the map, not sure if this is related. If I see anything else I will update.

**Comment by mc-funk** [comment]
Closing this as we have not seen more of these reports since this morning.
