### ISSUE TITLE
Trouble accessing map from school laptop

### ISSUE THREAD

**Issue by andyinabox** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#9]
> This is not a big deal at all but seems worth sharing: one of our monitors is a teacher working from a school-issued laptop and he cannot open the map. He shared it with several coworkers and they can't either. He has no issue from any other device, and he knows his school has some fairly intense locks on stuff. If that's a "haha oh right we could probably just change ____ and fix it," awesome; if that would take a lot more investigating to find out or address, it's not an issue

**Comment by jasonthibeault** [comment]
Looks like by @comeoneileen 's screenshot that some part of the tech stack (maybe mapbox, maybe the counter?) was flagged as unsafe by the school's filtering software. Not sure what we can do to mitigate without further information about what it was flagging on specifically, nor what can be done about it.

**Comment by andyinabox** [comment]
@jasonthibeault can you post the screenshtot here?

**Comment by jasonthibeault** [comment]
Here's what she sent -- but it doesn't have sufficient information to tell what is causing it. I asked Eileen for the info under "Diagnostic Info" and will forward when she gets it.

![blake-uni](https://user-images.githubusercontent.com/6886202/83689086-113b0b80-a5b4-11ea-8802-fa25c740bb8e.png)

**Comment by jasonthibeault** [comment]
FYI I tested against Google's Transparency Report tool and it says no unsafe content found: https://transparencyreport.google.com/safe-browsing/search?url=twin-cities-mutual-aid.org

**Comment by kmarekspartz** [comment]
What might be under the `Diagnostic Info` link?

Also wondering if any of the other domains linked are also blocked:
- https://api.mapbox.com
- https://cdn.jsdeliver.net
- https://counter.websiteout.net
- https://cdnjs.cloudflare.com
- https://spreadsheets.google.com
- https://events.mapbox.com

**Comment by kmarekspartz** [comment]
Some of the stuff from the other sites could be vended on our side, but it doesn't all have to be.

**Comment by kmarekspartz** [comment]
#15 will vend most of the dependencies. It will be worth rechecking after that.

**Comment by experimatt** [comment]
Think we can close this, or is there something still to be done here?

**Comment by jasonthibeault** [comment]
I'm going to check back with the reporter and close if it can't be duplicated

**Comment by experimatt** [comment]
@jasonthibeault safe to assume we can close now?
