### ISSUE TITLE
Error logging/notification

### ISSUE THREAD

**Issue by andyinabox** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#91]
Since our persistence layer (Google Sheets) is pretty error-prone, I think it would be really helpful if we could set up a service to notify us if there are errors in the production app. I know these exist but don't know anything about them ... ideally something we could plug into slack.

**Comment by jdalt** [comment]
@experimatt Is it time to reach out to the https://trackjs.com/ people? I've also used Airbrake for FE js logging before.

**Comment by experimatt** [comment]
@jdalt Our friend Todd already said he'd hook us up with a free account. We just need to create one and then I'll send over the email or whatever that it's associated with. Jacob you mind doing that?

**Comment by omawhite** [comment]
I have experience doing front end js logging from work, but its an internal tool, i would be interested in taking on this work, though i would have a bit of a learning curve learning to use track js or something.

**Comment by experimatt** [comment]
I've used trackjs before and it's fantastic. super easy to implement and quickly gives us actionable info on errors users are getting client side. it's what I used to identify and fix some issues with OMG Transit a while back. 5/5 would recommend

**Comment by omawhite** [comment]
That sounds good to me, if people are fine with me working on this just let me know when things are setup with the account. Looking at their site there doesn't seem to be a free option so i'm guessing i need to wait till we are set up.

**Comment by experimatt** [comment]
@omawhite the implementation is really simple IIRC. Depending on which email we should use, it's possible that jacob doesn't need to be the person to set it up. Like if we use the support@tcmap email

**Comment by kmarekspartz** [comment]
Do they have error -> Slack support? Then we can keep the email focused on human submitted issues.

**Comment by experimatt** [comment]
@kmarekspartz looks like there is a slack integration: https://frozenpizzaclub.slack.com/apps/ABDSHJXRP-trackjs

I just logged into my personal TrackJS account to look around again, and we can invite team members, too. I think we should proceed with creating an account and implementing it. The only question in my mind is which email address the root level organization account should belong to - my gut says support@tcmap.org. 

@jdalt think that sounds appropriate?

**Comment by experimatt** [comment]
@mc-funk approved using support@tcmap.org for the account so I just created one. I'll add folks to the team and share details shortly, but I don't need to be the person who implements it in the code. I would love for someone else to do that.

**Comment by experimatt** [comment]
@mc-funk @jdalt @andyinabox @omawhite @kmarekspartz OK I just created a TrackJS account and invited all of you to it. I don't need to do the implementation here, but the important thing is that you all have the right access to do the implementation.

I'll ping Todd at TrackJS so he hooks us up with a free account :)

**Comment by omawhite** [comment]
I'm in progress on this!

**Comment by experimatt** [comment]
Confirmed from Todd that we’re all set with a free/sponsored account.

**Comment by experimatt** [comment]
ENV variables added to Netlify and PR merged. 

The only remaining item is to add the TrackJS slack app, which I DMed Eric and Alison about to confirm that it's OK.

Great work, @omawhite! Thanks for jumping on this 🙌

**Comment by omawhite** [comment]
I would gladly dive into the slack integration as well, but I will be protesting this afternoon so I’m not sure what my availability will be for the rest of the day. If someone wants tackle it ASAP fee free.

**Comment by experimatt** [comment]
@omawhite I've got it. Glad you're protesting ✊

**Comment by experimatt** [comment]
TrackJS app notifications added to slack. we're all set! 🎉
