### ISSUE TITLE
Data validation

### ISSUE THREAD

**Issue by andyinabox** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#92]
I think it would be good if we had a module dedicated to validating the data we're getting from Google and raising detailed errors that make it easy for us to identify where the problem is. Combined with #91 this could go a long way toward avoiding lengthy outages.

**Comment by andyinabox** [comment]
Note that we'll definately need to catch the errors and log them rather than crashing the whole app.

**Comment by jdalt** [comment]
Extracting this to a module would be a good idea because we it would also give us a cleaner spot to build an API shim.

**Comment by cwood821** [comment]
This sort of captured my imagination a bit. I played around with an idea in a gist: 
https://gist.github.com/cwood821/6252c383557bc2f11413d260839b9556

The focus is mainly on iterating over a declared schema to validate an entire object. Schema's could support more complex types based on mapped validation functions. The example in the gist is `color`, but things like `Lng` and `Lat` could be done similarly. 

The actual validation doesn't do anything recursive (or properly catch all potential type errors), but that could be added.

I'm happy to iterate on this or throw it away depending on what y'all think.

**Comment by jdalt** [comment]
Given that we're pulling from sheets recursion wouldn't be necessary. Each row is flat.

**Comment by laniehei** [comment]
I saw that someone spun up a REST API using JS, and this project doesn't yet use backend code, so I'm not sure if this is helpful for this particular usecase: I have a lot of experience with working with the google sheets API, validating data using Go, and passing relevant errors to the frontend. New to the project, and I'm super unfamiliar with frontend validation tools, but I just thought I'd mention.

**Comment by experimatt** [comment]
I can help with data validation on the spreadsheet side, but I presume that will require some coordination on the Beaver side.

**Comment by mc-funk** [comment]
We can bring this up to the beaver team tomorrow. I think it would be a good thing to prioritize alongside other features, since it's pretty key for our ability to evolve, and I think we all recognize we're going to outgrow google sheets.
