### ISSUE TITLE
Fix TypeError: Cannot read property '$t' of undefined error

### ISSUE THREAD

**Issue by experimatt** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#95]
We're currently getting this error thrown in in the console in prod:
```
TypeError: Cannot read property '$t' of undefined
```

@alexives pinpointed it to `src/js/translator.js:223`. @andyinabox know this code the best because he wrote it, but if someone else wants to jump in before he or I can get to it, that would be fabulous.

**Comment by benjifs** [comment]
Should be fixed. The translations spreadsheet was missing headers for Ojibwe, Dakota, and Vietnamese

**Comment by experimatt** [comment]
@benjifs good eye, Benji! Good to know that _any_ changes to the spreadsheet can cause problems
